# Bosnian translation for cinder
# Copyright (c) 2011 Rosetta Contributors and Canonical Ltd 2011
# This file is distributed under the same license as the cinder package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version:  cinder\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2012-04-08 23:04+0000\n"
"PO-Revision-Date: 2012-01-19 20:22+0000\n"
"Last-Translator: yazar  <zrncescientiae@gmail.com>\n"
"Language-Team: Bosnian <bs@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"

#: cinder/context.py:59
#, python-format
msgid "Arguments dropped when creating context: %s"
msgstr ""

#: cinder/context.py:90
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: cinder/crypto.py:48
msgid "Filename of root CA"
msgstr ""

#: cinder/crypto.py:51
msgid "Filename of private key"
msgstr ""

#: cinder/crypto.py:54
msgid "Filename of root Certificate Revocation List"
msgstr ""

#: cinder/crypto.py:57
msgid "Where we keep our keys"
msgstr ""

#: cinder/crypto.py:60
msgid "Where we keep our root CA"
msgstr ""

#: cinder/crypto.py:63
msgid "Should we use a CA for each project?"
msgstr ""

#: cinder/crypto.py:67
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr ""

#: cinder/crypto.py:72
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr ""

#: cinder/crypto.py:292
#, python-format
msgid "Flags path: %s"
msgstr ""

#: cinder/exception.py:56
msgid "Unexpected error while running command."
msgstr "Neočekivana greška prilikom pokretanja komande."

#: cinder/exception.py:59
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: cinder/exception.py:94
msgid "DB exception wrapped."
msgstr ""

#: cinder/exception.py:155
msgid "An unknown exception occurred."
msgstr ""

#: cinder/exception.py:178
msgid "Failed to decrypt text"
msgstr ""

#: cinder/exception.py:182
msgid "Failed to paginate through images from image service"
msgstr ""

#: cinder/exception.py:186
msgid "Virtual Interface creation failed"
msgstr ""

#: cinder/exception.py:190
msgid "5 attempts to create virtual interfacewith unique mac address failed"
msgstr ""

#: cinder/exception.py:195
msgid "Connection to glance failed"
msgstr ""

#: cinder/exception.py:199
msgid "Connection to melange failed"
msgstr ""

#: cinder/exception.py:203
msgid "Not authorized."
msgstr ""

#: cinder/exception.py:208
msgid "User does not have admin privileges"
msgstr ""

#: cinder/exception.py:212
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: cinder/exception.py:216
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr ""

#: cinder/exception.py:220
msgid "Unacceptable parameters."
msgstr ""

#: cinder/exception.py:225
msgid "Invalid snapshot"
msgstr ""

#: cinder/exception.py:229
#, python-format
msgid "Hardware %(storage_id)s is not attached to anything"
msgstr ""

#: cinder/exception.py:233 cinder/api/openstack/compute/contrib/keypairs.py:113
msgid "Keypair data is invalid"
msgstr ""

#: cinder/exception.py:237
msgid "Failed to load data into json format"
msgstr ""

#: cinder/exception.py:241
msgid "The request is invalid."
msgstr ""

#: cinder/exception.py:245
#, python-format
msgid "Invalid signature %(signature)s for user %(user)s."
msgstr ""

#: cinder/exception.py:249
msgid "Invalid input received"
msgstr ""

#: cinder/exception.py:253
#, python-format
msgid "Invalid instance type %(instance_type)s."
msgstr ""

#: cinder/exception.py:257
msgid "Invalid storage type"
msgstr ""

#: cinder/exception.py:261
msgid "Invalid storage"
msgstr ""

#: cinder/exception.py:265
#, python-format
msgid "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"
msgstr ""

#: cinder/exception.py:269
#, python-format
msgid "Invalid IP protocol %(protocol)s."
msgstr ""

#: cinder/exception.py:273
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: cinder/exception.py:277
#, python-format
msgid "Invalid cidr %(cidr)s."
msgstr ""

#: cinder/exception.py:281
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: cinder/exception.py:285
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: cinder/exception.py:292
#, python-format
msgid "%(err)s"
msgstr ""

#: cinder/exception.py:296
#, python-format
msgid ""
"Cannot perform action '%(action)s' on aggregate %(aggregate_id)s. Reason:"
" %(reason)s."
msgstr ""

#: cinder/exception.py:301
#, python-format
msgid "Group not valid. Reason: %(reason)s"
msgstr ""

#: cinder/exception.py:305
#, python-format
msgid ""
"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while"
" the instance is in this state."
msgstr ""

#: cinder/exception.py:310
#, python-format
msgid "Instance %(instance_id)s is not running."
msgstr ""

#: cinder/exception.py:314
#, python-format
msgid "Instance %(instance_id)s is not suspended."
msgstr ""

#: cinder/exception.py:318
#, python-format
msgid "Instance %(instance_id)s is not in rescue mode"
msgstr ""

#: cinder/exception.py:322
msgid "Failed to suspend instance"
msgstr ""

#: cinder/exception.py:326
msgid "Failed to resume server"
msgstr ""

#: cinder/exception.py:330
msgid "Failed to reboot instance"
msgstr ""

#: cinder/exception.py:334
msgid "Failed to terminate instance"
msgstr ""

#: cinder/exception.py:338
msgid "Service is unavailable at this time."
msgstr ""

#: cinder/exception.py:342
msgid "Hardware service is unavailable at this time."
msgstr ""

#: cinder/exception.py:346
msgid "Compute service is unavailable at this time."
msgstr ""

#: cinder/exception.py:350
#, python-format
msgid "Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."
msgstr ""

#: cinder/exception.py:355
msgid "Destination compute host is unavailable at this time."
msgstr ""

#: cinder/exception.py:359
msgid "Original compute host is unavailable at this time."
msgstr ""

#: cinder/exception.py:363
msgid "The supplied hypervisor type of is invalid."
msgstr ""

#: cinder/exception.py:367
msgid "The instance requires a newer hypervisor version than has been provided."
msgstr ""

#: cinder/exception.py:372
#, python-format
msgid ""
"The supplied disk path (%(path)s) already exists, it is expected not to "
"exist."
msgstr ""

#: cinder/exception.py:377
#, python-format
msgid "The supplied device path (%(path)s) is invalid."
msgstr ""

#: cinder/exception.py:381
#, python-format
msgid "The supplied device (%(device)s) is busy."
msgstr ""

#: cinder/exception.py:385
msgid "Unacceptable CPU info"
msgstr ""

#: cinder/exception.py:389
#, python-format
msgid "%(address)s is not a valid IP v4/6 address."
msgstr ""

#: cinder/exception.py:393
#, python-format
msgid ""
"VLAN tag is not appropriate for the port group %(bridge)s. Expected VLAN "
"tag is %(tag)s, but the one associated with the port group is %(pgroup)s."
msgstr ""

#: cinder/exception.py:399
#, python-format
msgid ""
"vSwitch which contains the port group %(bridge)s is not associated with "
"the desired physical adapter. Expected vSwitch is %(expected)s, but the "
"one associated is %(actual)s."
msgstr ""

#: cinder/exception.py:406
#, python-format
msgid "Disk format %(disk_format)s is not acceptable"
msgstr ""

#: cinder/exception.py:410
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: cinder/exception.py:414
#, python-format
msgid "Instance %(instance_id)s is unacceptable: %(reason)s"
msgstr ""

#: cinder/exception.py:418
#, python-format
msgid "Ec2 id %(ec2_id)s is unacceptable."
msgstr ""

#: cinder/exception.py:422
msgid "Resource could not be found."
msgstr ""

#: cinder/exception.py:427
#, python-format
msgid "Required flag %(flag)s not set."
msgstr ""

#: cinder/exception.py:431
#, python-format
msgid "Hardware %(storage_id)s could not be found."
msgstr ""

#: cinder/exception.py:435
#, python-format
msgid "Unable to locate account %(account_name)s on Solidfire device"
msgstr ""

#: cinder/exception.py:440
#, python-format
msgid "Hardware not found for instance %(instance_id)s."
msgstr ""

#: cinder/exception.py:444
#, python-format
msgid "Hardware %(storage_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: cinder/exception.py:449
msgid "Zero storage types found."
msgstr ""

#: cinder/exception.py:453
#, python-format
msgid "Hardware type %(storage_type_id)s could not be found."
msgstr ""

#: cinder/exception.py:457
#, python-format
msgid "Hardware type with name %(storage_type_name)s could not be found."
msgstr ""

#: cinder/exception.py:462
#, python-format
msgid ""
"Hardware Type %(storage_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: cinder/exception.py:467
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: cinder/exception.py:471
#, python-format
msgid "deleting storage %(storage_name)s that has snapshot"
msgstr ""

#: cinder/exception.py:475
#, python-format
msgid "deleting snapshot %(snapshot_name)s that has dependent storages"
msgstr ""

#: cinder/exception.py:480
#, python-format
msgid "No target id found for storage %(storage_id)s."
msgstr ""

#: cinder/exception.py:484
#, python-format
msgid "No disk at %(location)s"
msgstr ""

#: cinder/exception.py:488
#, python-format
msgid "Could not find a handler for %(driver_type)s storage."
msgstr ""

#: cinder/exception.py:492
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: cinder/exception.py:496
msgid ""
"Some images have been stored via hrefs. This version of the api does not "
"support displaying image hrefs."
msgstr ""

#: cinder/exception.py:501
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: cinder/exception.py:505
#, python-format
msgid "Kernel not found for image %(image_id)s."
msgstr ""

#: cinder/exception.py:509
#, python-format
msgid "User %(user_id)s could not be found."
msgstr ""

#: cinder/exception.py:513
#, python-format
msgid "Project %(project_id)s could not be found."
msgstr ""

#: cinder/exception.py:517
#, python-format
msgid "User %(user_id)s is not a member of project %(project_id)s."
msgstr ""

#: cinder/exception.py:521
#, python-format
msgid "Role %(role_id)s could not be found."
msgstr ""

#: cinder/exception.py:525
msgid "Cannot find SR to read/write VDI."
msgstr ""

#: cinder/exception.py:529
#, python-format
msgid "%(req)s is required to create a network."
msgstr ""

#: cinder/exception.py:533
#, python-format
msgid "Network %(network_id)s could not be found."
msgstr ""

#: cinder/exception.py:537
#, python-format
msgid "Network could not be found for bridge %(bridge)s"
msgstr ""

#: cinder/exception.py:541
#, python-format
msgid "Network could not be found for uuid %(uuid)s"
msgstr ""

#: cinder/exception.py:545
#, python-format
msgid "Network could not be found with cidr %(cidr)s."
msgstr ""

#: cinder/exception.py:549
#, python-format
msgid "Network could not be found for instance %(instance_id)s."
msgstr ""

#: cinder/exception.py:553
msgid "No networks defined."
msgstr ""

#: cinder/exception.py:557
#, python-format
msgid ""
"Either Network uuid %(network_uuid)s is not present or is not assigned to"
" the project %(project_id)s."
msgstr ""

#: cinder/exception.py:562
#, python-format
msgid "Host is not set to the network (%(network_id)s)."
msgstr ""

#: cinder/exception.py:566
#, python-format
msgid "Network %(network)s has active ports, cannot delete."
msgstr ""

#: cinder/exception.py:570
msgid "Could not find the datastore reference(s) which the VM uses."
msgstr ""

#: cinder/exception.py:574
#, python-format
msgid "No fixed IP associated with id %(id)s."
msgstr ""

#: cinder/exception.py:578
#, python-format
msgid "Fixed ip not found for address %(address)s."
msgstr ""

#: cinder/exception.py:582
#, python-format
msgid "Instance %(instance_id)s has zero fixed ips."
msgstr ""

#: cinder/exception.py:586
#, python-format
msgid "Network host %(host)s has zero fixed ips in network %(network_id)s."
msgstr ""

#: cinder/exception.py:591
#, python-format
msgid "Instance %(instance_id)s doesn't have fixed ip '%(ip)s'."
msgstr ""

#: cinder/exception.py:595
#, python-format
msgid "Host %(host)s has zero fixed ips."
msgstr ""

#: cinder/exception.py:599
#, python-format
msgid ""
"Fixed IP address (%(address)s) does not exist in network "
"(%(network_uuid)s)."
msgstr ""

#: cinder/exception.py:604
#, python-format
msgid "Fixed IP address %(address)s is already in use."
msgstr ""

#: cinder/exception.py:608
#, python-format
msgid "Fixed IP address %(address)s is invalid."
msgstr ""

#: cinder/exception.py:612
msgid "Zero fixed ips available."
msgstr ""

#: cinder/exception.py:616
msgid "Zero fixed ips could be found."
msgstr ""

#: cinder/exception.py:620
#, python-format
msgid "Floating ip not found for id %(id)s."
msgstr ""

#: cinder/exception.py:624
#, python-format
msgid "The DNS entry %(name)s already exists in domain %(domain)s."
msgstr ""

#: cinder/exception.py:628
#, python-format
msgid "Floating ip not found for address %(address)s."
msgstr ""

#: cinder/exception.py:632
#, python-format
msgid "Floating ip not found for host %(host)s."
msgstr ""

#: cinder/exception.py:636
msgid "Zero floating ips available."
msgstr ""

#: cinder/exception.py:640
#, python-format
msgid "Floating ip %(address)s is associated."
msgstr ""

#: cinder/exception.py:644
#, python-format
msgid "Floating ip %(address)s is not associated."
msgstr ""

#: cinder/exception.py:648
msgid "Zero floating ips exist."
msgstr ""

#: cinder/exception.py:652
#, python-format
msgid "Interface %(interface)s not found."
msgstr ""

#: cinder/exception.py:656
#, python-format
msgid "Keypair %(name)s not found for user %(user_id)s"
msgstr ""

#: cinder/exception.py:660
#, python-format
msgid "Certificate %(certificate_id)s not found."
msgstr ""

#: cinder/exception.py:664
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: cinder/exception.py:668
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: cinder/exception.py:672
#, python-format
msgid "Compute host %(host)s could not be found."
msgstr ""

#: cinder/exception.py:676
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: cinder/exception.py:680
#, python-format
msgid "Auth token %(token)s could not be found."
msgstr ""

#: cinder/exception.py:684
#, python-format
msgid "Access Key %(access_key)s could not be found."
msgstr ""

#: cinder/exception.py:688
msgid "Quota could not be found"
msgstr ""

#: cinder/exception.py:692
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: cinder/exception.py:696
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr ""

#: cinder/exception.py:700
#, python-format
msgid "Security group %(security_group_id)s not found."
msgstr ""

#: cinder/exception.py:704
#, python-format
msgid "Security group %(security_group_id)s not found for project %(project_id)s."
msgstr ""

#: cinder/exception.py:709
#, python-format
msgid "Security group with rule %(rule_id)s not found."
msgstr ""

#: cinder/exception.py:713
#, python-format
msgid ""
"Security group %(security_group_id)s is already associated with the "
"instance %(instance_id)s"
msgstr ""

#: cinder/exception.py:718
#, python-format
msgid ""
"Security group %(security_group_id)s is not associated with the instance "
"%(instance_id)s"
msgstr ""

#: cinder/exception.py:723
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: cinder/exception.py:727
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: cinder/exception.py:732
#, python-format
msgid "Console pool %(pool_id)s could not be found."
msgstr ""

#: cinder/exception.py:736
#, python-format
msgid ""
"Console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s not found."
msgstr ""

#: cinder/exception.py:742
#, python-format
msgid "Console %(console_id)s could not be found."
msgstr ""

#: cinder/exception.py:746
#, python-format
msgid "Console for instance %(instance_id)s could not be found."
msgstr ""

#: cinder/exception.py:750
#, python-format
msgid ""
"Console for instance %(instance_id)s in pool %(pool_id)s could not be "
"found."
msgstr ""

#: cinder/exception.py:755
#, python-format
msgid "Invalid console type %(console_type)s "
msgstr ""

#: cinder/exception.py:759
msgid "Zero instance types found."
msgstr ""

#: cinder/exception.py:763
#, python-format
msgid "Instance type %(instance_type_id)s could not be found."
msgstr ""

#: cinder/exception.py:767
#, python-format
msgid "Instance type with name %(instance_type_name)s could not be found."
msgstr ""

#: cinder/exception.py:772
#, python-format
msgid "Flavor %(flavor_id)s could not be found."
msgstr ""

#: cinder/exception.py:776
#, python-format
msgid "Cell %(cell_id)s could not be found."
msgstr ""

#: cinder/exception.py:780
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""

#: cinder/exception.py:784
#, python-format
msgid "Scheduler cost function %(cost_fn_str)s could not be found."
msgstr ""

#: cinder/exception.py:789
#, python-format
msgid "Scheduler weight flag not found: %(flag_name)s"
msgstr ""

#: cinder/exception.py:793
#, python-format
msgid "Instance %(instance_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: cinder/exception.py:798
#, python-format
msgid ""
"Instance Type %(instance_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: cinder/exception.py:803
msgid "LDAP object could not be found"
msgstr ""

#: cinder/exception.py:807
#, python-format
msgid "LDAP user %(user_id)s could not be found."
msgstr ""

#: cinder/exception.py:811
#, python-format
msgid "LDAP group %(group_id)s could not be found."
msgstr ""

#: cinder/exception.py:815
#, python-format
msgid "LDAP user %(user_id)s is not a member of group %(group_id)s."
msgstr ""

#: cinder/exception.py:819
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: cinder/exception.py:823
msgid "Zero files could be found."
msgstr ""

#: cinder/exception.py:827
#, python-format
msgid "Virtual switch associated with the network adapter %(adapter)s not found."
msgstr ""

#: cinder/exception.py:832
#, python-format
msgid "Network adapter %(adapter)s could not be found."
msgstr ""

#: cinder/exception.py:836
#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr ""

#: cinder/exception.py:840
msgid "Action not allowed."
msgstr ""

#: cinder/exception.py:844
#, python-format
msgid "Unable to use global role %(role_id)s"
msgstr ""

#: cinder/exception.py:848
msgid "Rotation is not allowed for snapshots"
msgstr ""

#: cinder/exception.py:852
msgid "Rotation param is required for backup image_type"
msgstr ""

#: cinder/exception.py:861
#, python-format
msgid "Key pair %(key_name)s already exists."
msgstr ""

#: cinder/exception.py:865
#, python-format
msgid "User %(user)s already exists."
msgstr ""

#: cinder/exception.py:869
#, python-format
msgid "LDAP user %(user)s already exists."
msgstr ""

#: cinder/exception.py:873
#, python-format
msgid "LDAP group %(group)s already exists."
msgstr ""

#: cinder/exception.py:877
#, python-format
msgid "User %(uid)s is already a member of the group %(group_dn)s"
msgstr ""

#: cinder/exception.py:882
#, python-format
msgid "Project %(project)s already exists."
msgstr ""

#: cinder/exception.py:886
#, python-format
msgid "Instance %(name)s already exists."
msgstr ""

#: cinder/exception.py:890
#, python-format
msgid "Instance Type %(name)s already exists."
msgstr ""

#: cinder/exception.py:894
#, python-format
msgid "Hardware Type %(name)s already exists."
msgstr ""

#: cinder/exception.py:898
#, python-format
msgid "%(path)s is on shared storage: %(reason)s"
msgstr ""

#: cinder/exception.py:902
msgid "Migration error"
msgstr ""

#: cinder/exception.py:906
#, python-format
msgid "Malformed message body: %(reason)s"
msgstr ""

#: cinder/exception.py:910
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: cinder/exception.py:914
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr ""

#: cinder/exception.py:918
msgid "When resizing, instances must change size!"
msgstr ""

#: cinder/exception.py:922
msgid "Image is larger than instance type allows"
msgstr ""

#: cinder/exception.py:926
msgid "1 or more Zones could not complete the request"
msgstr ""

#: cinder/exception.py:930
msgid "Instance type's memory is too small for requested image."
msgstr ""

#: cinder/exception.py:934
msgid "Instance type's disk is too small for requested image."
msgstr ""

#: cinder/exception.py:938
#, python-format
msgid "Insufficient free memory on compute node to start %(uuid)s."
msgstr ""

#: cinder/exception.py:942
msgid "Could not fetch bandwidth/cpu/disk metrics for this host."
msgstr ""

#: cinder/exception.py:946
#, python-format
msgid "No valid host was found. %(reason)s"
msgstr ""

#: cinder/exception.py:950
#, python-format
msgid "Host %(host)s is not up or doesn't exist."
msgstr ""

#: cinder/exception.py:954
msgid "Quota exceeded"
msgstr ""

#: cinder/exception.py:958
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: action '%(action)s' caused an error: "
"%(reason)s."
msgstr ""

#: cinder/exception.py:963
#, python-format
msgid "Aggregate %(aggregate_id)s could not be found."
msgstr ""

#: cinder/exception.py:967
#, python-format
msgid "Aggregate %(aggregate_name)s already exists."
msgstr ""

#: cinder/exception.py:971
#, python-format
msgid "Aggregate %(aggregate_id)s has no host %(host)s."
msgstr ""

#: cinder/exception.py:975
#, python-format
msgid "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: cinder/exception.py:980
#, python-format
msgid "Host %(host)s already member of another aggregate."
msgstr ""

#: cinder/exception.py:984
#, python-format
msgid "Aggregate %(aggregate_id)s already has host %(host)s."
msgstr ""

#: cinder/exception.py:988
#, python-format
msgid "Detected more than one storage with name %(vol_name)s"
msgstr ""

#: cinder/exception.py:992
#, python-format
msgid "Cannot create storage_type with name %(name)s and specs %(extra_specs)s"
msgstr ""

#: cinder/exception.py:997
msgid "Unable to create instance type"
msgstr ""

#: cinder/exception.py:1001
msgid "Bad response from SolidFire API"
msgstr ""

#: cinder/exception.py:1005
#, python-format
msgid "Error in SolidFire API response: status=%(status)s"
msgstr ""

#: cinder/exception.py:1009
#, python-format
msgid "Error in SolidFire API response: data=%(data)s"
msgstr ""

#: cinder/exception.py:1013
#, python-format
msgid "Detected existing vlan with id %(vlan)d"
msgstr ""

#: cinder/exception.py:1017
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: cinder/exception.py:1021
#, python-format
msgid "Invalid id: %(val)s (expecting \"i-...\")."
msgstr ""

#: cinder/exception.py:1025
#, python-format
msgid "Could not fetch image %(image)s"
msgstr ""

#: cinder/log.py:315
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: cinder/manager.py:146
#, python-format
msgid "Skipping %(full_task_name)s, %(ticks_to_skip)s ticks left until next run"
msgstr ""

#: cinder/manager.py:152
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr ""

#: cinder/manager.py:159
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: cinder/manager.py:203
msgid "Notifying Schedulers of capabilities ..."
msgstr ""

#: cinder/policy.py:30
msgid "JSON file representing policy"
msgstr ""

#: cinder/policy.py:33
msgid "Rule checked when requested rule is not found"
msgstr ""

#: cinder/service.py:137
msgid "SIGTERM received"
msgstr ""

#: cinder/service.py:177
#, python-format
msgid "Starting %(topic)s node (version %(vcs_string)s)"
msgstr ""

#: cinder/service.py:195
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: cinder/service.py:282
msgid "Service killed that has no database entry"
msgstr ""

#: cinder/service.py:319
msgid "The service database object disappeared, Recreating it."
msgstr ""

#: cinder/service.py:334
msgid "Recovered model server connection!"
msgstr ""

#: cinder/service.py:340
msgid "model server went away"
msgstr ""

#: cinder/service.py:433
msgid "Full set of FLAGS:"
msgstr ""

#: cinder/service.py:440
#, python-format
msgid "%(flag)s : FLAG SET "
msgstr ""

#: cinder/utils.py:79
#, python-format
msgid "Inner Exception: %s"
msgstr ""

#: cinder/utils.py:165
#, python-format
msgid "Fetching %s"
msgstr ""

#: cinder/utils.py:210
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: cinder/utils.py:220
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: cinder/utils.py:236 cinder/utils.py:315
#, python-format
msgid "Result was %s"
msgstr ""

#: cinder/utils.py:249
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: cinder/utils.py:291
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: cinder/utils.py:293
msgid "Environment not supported over SSH"
msgstr ""

#: cinder/utils.py:297
msgid "process_input not supported over SSH"
msgstr ""

#: cinder/utils.py:352
#, python-format
msgid "debug in callback: %s"
msgstr ""

#: cinder/utils.py:534
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: cinder/utils.py:537
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: cinder/utils.py:648
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: cinder/utils.py:659
#, python-format
msgid "backend %s"
msgstr ""

#: cinder/utils.py:709
msgid "in looping call"
msgstr ""

#: cinder/utils.py:927
#, python-format
msgid "Attempting to grab semaphore \"%(lock)s\" for method \"%(method)s\"..."
msgstr ""

#: cinder/utils.py:931
#, python-format
msgid "Got semaphore \"%(lock)s\" for method \"%(method)s\"..."
msgstr ""

#: cinder/utils.py:935
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\" for method \"%(method)s\"..."
msgstr ""

#: cinder/utils.py:942
#, python-format
msgid "Got file lock \"%(lock)s\" for method \"%(method)s\"..."
msgstr ""

#: cinder/utils.py:1001
#, python-format
msgid "Found sentinel %(filename)s for pid %(pid)s"
msgstr ""

#: cinder/utils.py:1008
#, python-format
msgid "Cleaned sentinel %(filename)s for pid %(pid)s"
msgstr ""

#: cinder/utils.py:1023
#, python-format
msgid "Found lockfile %(file)s with link count %(count)d"
msgstr ""

#: cinder/utils.py:1028
#, python-format
msgid "Cleaned lockfile %(file)s with link count %(count)d"
msgstr ""

#: cinder/utils.py:1138
#, python-format
msgid "Expected object of type: %s"
msgstr ""

#: cinder/utils.py:1169
#, python-format
msgid "Invalid server_string: %s"
msgstr ""

#: cinder/utils.py:1298
#, python-format
msgid "timefunc: '%(name)s' took %(total_time).2f secs"
msgstr ""

#: cinder/utils.py:1330
msgid "Original exception being dropped"
msgstr ""

#: cinder/utils.py:1461
#, python-format
msgid "Class %(fullname)s is deprecated: %(msg)s"
msgstr ""

#: cinder/utils.py:1463
#, python-format
msgid "Class %(fullname)s is deprecated"
msgstr ""

#: cinder/utils.py:1495
#, python-format
msgid "Function %(name)s in %(location)s is deprecated: %(msg)s"
msgstr ""

#: cinder/utils.py:1497
#, python-format
msgid "Function %(name)s in %(location)s is deprecated"
msgstr ""

#: cinder/utils.py:1681
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: cinder/wsgi.py:97
#, python-format
msgid "Started %(name)s on %(host)s:%(port)s"
msgstr ""

#: cinder/wsgi.py:108
msgid "Stopping WSGI server."
msgstr ""

#: cinder/wsgi.py:111
msgid "Stopping raw TCP server."
msgstr ""

#: cinder/wsgi.py:117
#, python-format
msgid "Starting TCP server %(arg0)s on %(host)s:%(port)s"
msgstr ""

#: cinder/wsgi.py:133
msgid "WSGI server has stopped."
msgstr ""

#: cinder/wsgi.py:211
msgid "You must implement __call__"
msgstr ""

#: cinder/api/direct.py:218
msgid "not available"
msgstr ""

#: cinder/api/direct.py:299
#, python-format
msgid "Returned non-serializeable type: %s"
msgstr ""

#: cinder/api/sizelimit.py:51
msgid "Request is too large."
msgstr ""

#: cinder/api/validator.py:142
#, python-format
msgid "%(key)s with value %(value)s failed validator  %(validator)s"
msgstr ""

#: cinder/api/ec2/__init__.py:73
#, python-format
msgid "%(code)s: %(message)s"
msgstr ""

#: cinder/api/ec2/__init__.py:95
#, python-format
msgid "FaultWrapper: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:170
msgid "Too many failed authentications."
msgstr ""

#: cinder/api/ec2/__init__.py:180
#, python-format
msgid ""
"Access key %(access_key)s has had %(failures)d failed authentications and"
" will be locked out for %(lock_mins)d minutes."
msgstr ""

#: cinder/api/ec2/__init__.py:267
msgid "Signature not provided"
msgstr ""

#: cinder/api/ec2/__init__.py:271
msgid "Access key not provided"
msgstr ""

#: cinder/api/ec2/__init__.py:306 cinder/api/ec2/__init__.py:319
msgid "Failure communicating with keystone"
msgstr ""

#: cinder/api/ec2/__init__.py:388
#, python-format
msgid "Authentication Failure: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:404
#, python-format
msgid "Authenticated Request For %(uname)s:%(pname)s)"
msgstr ""

#: cinder/api/ec2/__init__.py:435
#, python-format
msgid "action: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:437
#, python-format
msgid "arg: %(key)s\t\tval: %(value)s"
msgstr ""

#: cinder/api/ec2/__init__.py:512
#, python-format
msgid "Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""

#: cinder/api/ec2/__init__.py:584
#, python-format
msgid "InstanceNotFound raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:590
#, python-format
msgid "HardwareNotFound raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:596
#, python-format
msgid "SnapshotNotFound raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:602
#, python-format
msgid "NotFound raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:605
#, python-format
msgid "EC2APIError raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:613
#, python-format
msgid "KeyPairExists raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:617
#, python-format
msgid "InvalidParameterValue raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:621
#, python-format
msgid "InvalidPortRange raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:625
#, python-format
msgid "NotAuthorized raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:629
#, python-format
msgid "InvalidRequest raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:633
#, python-format
msgid "QuotaError raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:637
#, python-format
msgid "Invalid id: bogus (expecting \"i-...\"): %s"
msgstr ""

#: cinder/api/ec2/__init__.py:646
#, python-format
msgid "Unexpected error raised: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:647
#, python-format
msgid "Environment: %s"
msgstr ""

#: cinder/api/ec2/__init__.py:649 cinder/api/metadata/handler.py:248
msgid "An unknown error has occurred. Please try your request again."
msgstr ""

#: cinder/api/ec2/apirequest.py:64
#, python-format
msgid "Unsupported API request: controller = %(controller)s, action = %(action)s"
msgstr ""

#: cinder/api/ec2/cloud.py:336
#, python-format
msgid "Create snapshot of storage %s"
msgstr ""

#: cinder/api/ec2/cloud.py:372
#, python-format
msgid ""
"Value (%s) for KeyName is invalid. Content limited to Alphanumeric "
"character, spaces, dashes, and underscore."
msgstr ""

#: cinder/api/ec2/cloud.py:378
#, python-format
msgid "Value (%s) for Keyname is invalid. Length exceeds maximum of 255."
msgstr ""

#: cinder/api/ec2/cloud.py:382
#, python-format
msgid "Create key pair %s"
msgstr ""

#: cinder/api/ec2/cloud.py:391
#, python-format
msgid "Import key %s"
msgstr ""

#: cinder/api/ec2/cloud.py:409
#, python-format
msgid "Delete key pair %s"
msgstr ""

#: cinder/api/ec2/cloud.py:551
msgid "Invalid CIDR"
msgstr ""

#: cinder/api/ec2/cloud.py:639 cinder/api/ec2/cloud.py:693
#: cinder/api/ec2/cloud.py:800
msgid "Not enough parameters, need group_name or group_id"
msgstr ""

#: cinder/api/ec2/cloud.py:654
#: cinder/api/openstack/compute/contrib/security_groups.py:517
#, python-format
msgid "Revoke security group ingress %s"
msgstr ""

#: cinder/api/ec2/cloud.py:666 cinder/api/ec2/cloud.py:719
#, python-format
msgid "%s Not enough parameters to build a valid rule"
msgstr ""

#: cinder/api/ec2/cloud.py:684 cinder/api/ec2/cloud.py:744
msgid "No rule for the specified parameters."
msgstr ""

#: cinder/api/ec2/cloud.py:708
#: cinder/api/openstack/compute/contrib/security_groups.py:354
#, python-format
msgid "Authorize security group ingress %s"
msgstr ""

#: cinder/api/ec2/cloud.py:725
#, python-format
msgid "%s - This rule already exists in group"
msgstr ""

#: cinder/api/ec2/cloud.py:769
#, python-format
msgid ""
"Value (%s) for parameter GroupName is invalid. Content limited to "
"Alphanumeric characters, spaces, dashes, and underscores."
msgstr ""

#: cinder/api/ec2/cloud.py:776
#, python-format
msgid ""
"Value (%s) for parameter GroupName is invalid. Length exceeds maximum of "
"255."
msgstr ""

#: cinder/api/ec2/cloud.py:780
#: cinder/api/openstack/compute/contrib/security_groups.py:292
#, python-format
msgid "Create Security Group %s"
msgstr ""

#: cinder/api/ec2/cloud.py:783
#, python-format
msgid "group %s already exists"
msgstr ""

#: cinder/api/ec2/cloud.py:815
#: cinder/api/openstack/compute/contrib/security_groups.py:245
#, python-format
msgid "Delete security group %s"
msgstr ""

#: cinder/api/ec2/cloud.py:823 cinder/compute/manager.py:1630
#, python-format
msgid "Get console output for instance %s"
msgstr ""

#: cinder/api/ec2/cloud.py:894
#, python-format
msgid "Create storage from snapshot %s"
msgstr ""

#: cinder/api/ec2/cloud.py:898 cinder/api/openstack/compute/contrib/storages.py:186
#: cinder/api/openstack/storage/storages.py:222
#, python-format
msgid "Create storage of %s GB"
msgstr ""

#: cinder/api/ec2/cloud.py:921
msgid "Delete Failed"
msgstr ""

#: cinder/api/ec2/cloud.py:931
#, python-format
msgid "Attach storage %(storage_id)s to instance %(instance_id)s at %(device)s"
msgstr ""

#: cinder/api/ec2/cloud.py:939
msgid "Attach Failed."
msgstr ""

#: cinder/api/ec2/cloud.py:952 cinder/api/openstack/compute/contrib/storages.py:366
#, python-format
msgid "Detach storage %s"
msgstr ""

#: cinder/api/ec2/cloud.py:959
msgid "Detach Hardware Failed."
msgstr ""

#: cinder/api/ec2/cloud.py:984 cinder/api/ec2/cloud.py:1041
#: cinder/api/ec2/cloud.py:1518 cinder/api/ec2/cloud.py:1533
#, python-format
msgid "attribute not supported: %s"
msgstr ""

#: cinder/api/ec2/cloud.py:1107
#, python-format
msgid "vol = %s\n"
msgstr ""

#: cinder/api/ec2/cloud.py:1255
msgid "Allocate address"
msgstr ""

#: cinder/api/ec2/cloud.py:1267
#, python-format
msgid "Release address %s"
msgstr ""

#: cinder/api/ec2/cloud.py:1272
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr ""

#: cinder/api/ec2/cloud.py:1282
#, python-format
msgid "Disassociate address %s"
msgstr ""

#: cinder/api/ec2/cloud.py:1308
msgid "Image must be available"
msgstr ""

#: cinder/api/ec2/cloud.py:1329
msgid "Going to start terminating instances"
msgstr ""

#: cinder/api/ec2/cloud.py:1343
#, python-format
msgid "Reboot instance %r"
msgstr ""

#: cinder/api/ec2/cloud.py:1354
msgid "Going to stop instances"
msgstr ""

#: cinder/api/ec2/cloud.py:1365
msgid "Going to start instances"
msgstr ""

#: cinder/api/ec2/cloud.py:1455
#, python-format
msgid "De-registering image %s"
msgstr ""

#: cinder/api/ec2/cloud.py:1471
msgid "imageLocation is required"
msgstr ""

#: cinder/api/ec2/cloud.py:1490
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr ""

#: cinder/api/ec2/cloud.py:1536
msgid "user or group not specified"
msgstr ""

#: cinder/api/ec2/cloud.py:1538
msgid "only group \"all\" is supported"
msgstr ""

#: cinder/api/ec2/cloud.py:1540
msgid "operation_type must be add or remove"
msgstr ""

#: cinder/api/ec2/cloud.py:1542
#, python-format
msgid "Updating image %s publicity"
msgstr ""

#: cinder/api/ec2/cloud.py:1555
#, python-format
msgid "Not allowed to modify attributes for image %s"
msgstr ""

#: cinder/api/ec2/cloud.py:1603
#, python-format
msgid "Couldn't stop instance with in %d sec"
msgstr ""

#: cinder/api/metadata/handler.py:246 cinder/api/metadata/handler.py:253
#, python-format
msgid "Failed to get metadata for ip: %s"
msgstr ""

#: cinder/api/openstack/__init__.py:43
#, python-format
msgid "Caught error: %s"
msgstr ""

#: cinder/api/openstack/__init__.py:45 cinder/api/openstack/wsgi.py:886
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: cinder/api/openstack/__init__.py:94
msgid "Must specify an ExtensionManager class"
msgstr ""

#: cinder/api/openstack/__init__.py:105
#, python-format
msgid "Extended resource: %s"
msgstr ""

#: cinder/api/openstack/__init__.py:130
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: cinder/api/openstack/__init__.py:135
#, python-format
msgid "Extension %(ext_name)s extending resource: %(collection)s"
msgstr ""

#: cinder/api/openstack/auth.py:90
#, python-format
msgid "%(user_id)s could not be found with token '%(token)s'"
msgstr ""

#: cinder/api/openstack/auth.py:134
#, python-format
msgid "%(user_id)s must be an admin or a member of %(project_id)s"
msgstr ""

#: cinder/api/openstack/auth.py:152
msgid "Authentication requests must be made against a version root (e.g. /v2)."
msgstr ""

#: cinder/api/openstack/auth.py:167
#, python-format
msgid "Could not find %s in request."
msgstr ""

#: cinder/api/openstack/auth.py:191
#, python-format
msgid "Successfully authenticated '%s'"
msgstr ""

#: cinder/api/openstack/auth.py:241
msgid "User not found with provided API key."
msgstr ""

#: cinder/api/openstack/auth.py:258
#, python-format
msgid "Provided API key is valid, but not for user '%(username)s'"
msgstr ""

#: cinder/api/openstack/common.py:133 cinder/api/openstack/common.py:167
msgid "limit param must be an integer"
msgstr ""

#: cinder/api/openstack/common.py:136 cinder/api/openstack/common.py:171
msgid "limit param must be positive"
msgstr ""

#: cinder/api/openstack/common.py:161
msgid "offset param must be an integer"
msgstr ""

#: cinder/api/openstack/common.py:175
msgid "offset param must be positive"
msgstr ""

#: cinder/api/openstack/common.py:203
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: cinder/api/openstack/common.py:243
#, python-format
msgid "href %s does not contain version"
msgstr ""

#: cinder/api/openstack/common.py:278
msgid "Image metadata limit exceeded"
msgstr ""

#: cinder/api/openstack/common.py:295
#, python-format
msgid "Converting nw_info: %s"
msgstr ""

#: cinder/api/openstack/common.py:305
#, python-format
msgid "Converted networks: %s"
msgstr ""

#: cinder/api/openstack/common.py:338
#, python-format
msgid "Cannot '%(action)s' while instance is in %(attr)s %(state)s"
msgstr ""

#: cinder/api/openstack/common.py:341
#, python-format
msgid "Instance is in an invalid state for '%(action)s'"
msgstr ""

#: cinder/api/openstack/common.py:421
msgid "Rejecting snapshot request, snapshots currently disabled"
msgstr ""

#: cinder/api/openstack/common.py:423
msgid "Instance snapshots are not permitted at this time."
msgstr ""

#: cinder/api/openstack/extensions.py:188
#, python-format
msgid "Loaded extension: %s"
msgstr ""

#: cinder/api/openstack/extensions.py:225
#, python-format
msgid "Ext name: %s"
msgstr ""

#: cinder/api/openstack/extensions.py:226
#, python-format
msgid "Ext alias: %s"
msgstr ""

#: cinder/api/openstack/extensions.py:227
#, python-format
msgid "Ext description: %s"
msgstr ""

#: cinder/api/openstack/extensions.py:229
#, python-format
msgid "Ext namespace: %s"
msgstr ""

#: cinder/api/openstack/extensions.py:230
#, python-format
msgid "Ext updated: %s"
msgstr ""

#: cinder/api/openstack/extensions.py:232
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: cinder/api/openstack/extensions.py:246
#, python-format
msgid "Loading extension %s"
msgstr ""

#: cinder/api/openstack/extensions.py:252
#, python-format
msgid "Calling extension factory %s"
msgstr ""

#: cinder/api/openstack/extensions.py:264
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: cinder/api/openstack/extensions.py:344
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: cinder/api/openstack/extensions.py:368
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: cinder/api/openstack/wsgi.py:135 cinder/api/openstack/wsgi.py:538
msgid "cannot understand JSON"
msgstr ""

#: cinder/api/openstack/wsgi.py:159
#: cinder/api/openstack/compute/contrib/hosts.py:86
msgid "cannot understand XML"
msgstr ""

#: cinder/api/openstack/wsgi.py:543
msgid "too many body keys"
msgstr ""

#: cinder/api/openstack/wsgi.py:582
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: cinder/api/openstack/wsgi.py:586
#, python-format
msgid "Fault thrown: %s"
msgstr ""

#: cinder/api/openstack/wsgi.py:589
#, python-format
msgid "HTTP exception thrown: %s"
msgstr ""

#: cinder/api/openstack/wsgi.py:697
msgid "Unrecognized Content-Type provided in request"
msgstr ""

#: cinder/api/openstack/wsgi.py:701
msgid "No Content-Type provided in request"
msgstr ""

#: cinder/api/openstack/wsgi.py:705
msgid "Empty body provided in request"
msgstr ""

#: cinder/api/openstack/wsgi.py:816
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: cinder/api/openstack/wsgi.py:819 cinder/api/openstack/wsgi.py:832
#: cinder/api/openstack/compute/server_metadata.py:58
#: cinder/api/openstack/compute/server_metadata.py:76
#: cinder/api/openstack/compute/server_metadata.py:101
#: cinder/api/openstack/compute/server_metadata.py:126
#: cinder/api/openstack/compute/contrib/admin_actions.py:211
#: cinder/api/openstack/compute/contrib/console_output.py:52
msgid "Malformed request body"
msgstr ""

#: cinder/api/openstack/wsgi.py:829
msgid "Unsupported Content-Type"
msgstr ""

#: cinder/api/openstack/wsgi.py:841
msgid "Malformed request url"
msgstr ""

#: cinder/api/openstack/wsgi.py:889
#, python-format
msgid "%(url)s returned a fault: %(e)s"
msgstr ""

#: cinder/api/openstack/xmlutil.py:265
msgid "element is not a child"
msgstr ""

#: cinder/api/openstack/xmlutil.py:414
msgid "root element selecting a list"
msgstr ""

#: cinder/api/openstack/xmlutil.py:739
#, python-format
msgid "Template tree mismatch; adding slave %(slavetag)s to master %(mastertag)s"
msgstr ""

#: cinder/api/openstack/xmlutil.py:858
msgid "subclasses must implement construct()!"
msgstr ""

#: cinder/api/openstack/compute/extensions.py:29
#: cinder/api/openstack/storage/extensions.py:29
msgid "Initializing extension manager."
msgstr ""

#: cinder/api/openstack/compute/image_metadata.py:40
#: cinder/api/openstack/compute/images.py:146
#: cinder/api/openstack/compute/images.py:161
msgid "Image not found."
msgstr ""

#: cinder/api/openstack/compute/image_metadata.py:79
msgid "Incorrect request body format"
msgstr ""

#: cinder/api/openstack/compute/image_metadata.py:83
#: cinder/api/openstack/compute/server_metadata.py:80
#: cinder/api/openstack/compute/contrib/flavorextraspecs.py:79
#: cinder/api/openstack/compute/contrib/storagetypes.py:188
msgid "Request body and URI mismatch"
msgstr ""

#: cinder/api/openstack/compute/image_metadata.py:86
#: cinder/api/openstack/compute/server_metadata.py:84
#: cinder/api/openstack/compute/contrib/flavorextraspecs.py:82
#: cinder/api/openstack/compute/contrib/storagetypes.py:191
msgid "Request body contains too many items"
msgstr ""

#: cinder/api/openstack/compute/image_metadata.py:111
msgid "Invalid metadata key"
msgstr ""

#: cinder/api/openstack/compute/ips.py:74
msgid "Instance does not exist"
msgstr ""

#: cinder/api/openstack/compute/ips.py:97
msgid "Instance is not a member of specified network"
msgstr ""

#: cinder/api/openstack/compute/limits.py:140
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: cinder/api/openstack/compute/limits.py:266
msgid "This request was rate-limited."
msgstr ""

#: cinder/api/openstack/compute/server_metadata.py:38
#: cinder/api/openstack/compute/server_metadata.py:122
#: cinder/api/openstack/compute/server_metadata.py:159
msgid "Server does not exist"
msgstr ""

#: cinder/api/openstack/compute/server_metadata.py:141
#: cinder/api/openstack/compute/server_metadata.py:152
msgid "Metadata item was not found"
msgstr ""

#: cinder/api/openstack/compute/servers.py:425
#, python-format
msgid "Invalid server status: %(status)s"
msgstr ""

#: cinder/api/openstack/compute/servers.py:433
msgid "Invalid changes-since value"
msgstr ""

#: cinder/api/openstack/compute/servers.py:483
msgid "Personality file limit exceeded"
msgstr ""

#: cinder/api/openstack/compute/servers.py:485
msgid "Personality file path too long"
msgstr ""

#: cinder/api/openstack/compute/servers.py:487
msgid "Personality file content too long"
msgstr ""

#: cinder/api/openstack/compute/servers.py:501
msgid "Server name is not a string or unicode"
msgstr ""

#: cinder/api/openstack/compute/servers.py:505
msgid "Server name is an empty string"
msgstr ""

#: cinder/api/openstack/compute/servers.py:509
msgid "Server name must be less than 256 characters."
msgstr ""

#: cinder/api/openstack/compute/servers.py:527
#, python-format
msgid "Bad personality format: missing %s"
msgstr ""

#: cinder/api/openstack/compute/servers.py:530
msgid "Bad personality format"
msgstr ""

#: cinder/api/openstack/compute/servers.py:535
#, python-format
msgid "Personality content for %s cannot be decoded"
msgstr ""

#: cinder/api/openstack/compute/servers.py:550
#, python-format
msgid "Bad networks format: network uuid is not in proper format (%s)"
msgstr ""

#: cinder/api/openstack/compute/servers.py:559
#, python-format
msgid "Invalid fixed IP address (%s)"
msgstr ""

#: cinder/api/openstack/compute/servers.py:566
#, python-format
msgid "Duplicate networks (%s) are not allowed"
msgstr ""

#: cinder/api/openstack/compute/servers.py:572
#, python-format
msgid "Bad network format: missing %s"
msgstr ""

#: cinder/api/openstack/compute/servers.py:575
msgid "Bad networks format"
msgstr ""

#: cinder/api/openstack/compute/servers.py:587
msgid "Userdata content cannot be decoded"
msgstr ""

#: cinder/api/openstack/compute/servers.py:594
msgid "accessIPv4 is not proper IPv4 format"
msgstr ""

#: cinder/api/openstack/compute/servers.py:601
msgid "accessIPv6 is not proper IPv6 format"
msgstr ""

#: cinder/api/openstack/compute/servers.py:633
msgid "Server name is not defined"
msgstr ""

#: cinder/api/openstack/compute/servers.py:675
#: cinder/api/openstack/compute/servers.py:740
msgid "Invalid flavorRef provided."
msgstr ""

#: cinder/api/openstack/compute/servers.py:737
msgid "Can not find requested image"
msgstr ""

#: cinder/api/openstack/compute/servers.py:743
msgid "Invalid key_name provided."
msgstr ""

#: cinder/api/openstack/compute/servers.py:829
#: cinder/api/openstack/compute/servers.py:849
msgid "Instance has not been resized."
msgstr ""

#: cinder/api/openstack/compute/servers.py:835
#, python-format
msgid "Error in confirm-resize %s"
msgstr ""

#: cinder/api/openstack/compute/servers.py:855
#, python-format
msgid "Error in revert-resize %s"
msgstr ""

#: cinder/api/openstack/compute/servers.py:868
msgid "Argument 'type' for reboot is not HARD or SOFT"
msgstr ""

#: cinder/api/openstack/compute/servers.py:872
msgid "Missing argument 'type' for reboot"
msgstr ""

#: cinder/api/openstack/compute/servers.py:885
#, python-format
msgid "Error in reboot %s"
msgstr ""

#: cinder/api/openstack/compute/servers.py:897
msgid "Unable to locate requested flavor."
msgstr ""

#: cinder/api/openstack/compute/servers.py:900
msgid "Resize requires a change in size."
msgstr ""

#: cinder/api/openstack/compute/servers.py:924
msgid "Malformed server entity"
msgstr ""

#: cinder/api/openstack/compute/servers.py:931
msgid "Missing imageRef attribute"
msgstr ""

#: cinder/api/openstack/compute/servers.py:940
msgid "Invalid imageRef provided."
msgstr ""

#: cinder/api/openstack/compute/servers.py:949
msgid "Missing flavorRef attribute"
msgstr ""

#: cinder/api/openstack/compute/servers.py:962
msgid "No adminPass was specified"
msgstr ""

#: cinder/api/openstack/compute/servers.py:966
#: cinder/api/openstack/compute/servers.py:1144
msgid "Invalid adminPass"
msgstr ""

#: cinder/api/openstack/compute/servers.py:980
msgid "Unable to parse metadata key/value pairs."
msgstr ""

#: cinder/api/openstack/compute/servers.py:993
msgid "Resize request has invalid 'flavorRef' attribute."
msgstr ""

#: cinder/api/openstack/compute/servers.py:996
msgid "Resize requests require 'flavorRef' attribute."
msgstr ""

#: cinder/api/openstack/compute/servers.py:1014
#: cinder/api/openstack/compute/contrib/aggregates.py:142
#: cinder/api/openstack/compute/contrib/networks.py:65
msgid "Invalid request body"
msgstr ""

#: cinder/api/openstack/compute/servers.py:1019
msgid "Could not parse imageRef from request."
msgstr ""

#: cinder/api/openstack/compute/servers.py:1071
msgid "Instance could not be found"
msgstr ""

#: cinder/api/openstack/compute/servers.py:1074
msgid "Cannot find image for rebuild"
msgstr ""

#: cinder/api/openstack/compute/servers.py:1103
msgid "createImage entity requires name attribute"
msgstr ""

#: cinder/api/openstack/compute/servers.py:1112
#: cinder/api/openstack/compute/contrib/admin_actions.py:238
msgid "Invalid metadata"
msgstr ""

#: cinder/api/openstack/compute/servers.py:1167
#, python-format
msgid "Removing options '%(unk_opt_str)s' from query"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:60
#, python-format
msgid "Compute.api::pause %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:77
#, python-format
msgid "Compute.api::unpause %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:94
#, python-format
msgid "compute.api::suspend %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:111
#, python-format
msgid "compute.api::resume %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:127
#, python-format
msgid "Error in migrate %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:141
#, python-format
msgid "Compute.api::reset_network %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:154
#: cinder/api/openstack/compute/contrib/admin_actions.py:170
#: cinder/api/openstack/compute/contrib/admin_actions.py:186
#: cinder/api/openstack/compute/contrib/multinic.py:41
#: cinder/api/openstack/compute/contrib/rescue.py:44
msgid "Server not found"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:157
#, python-format
msgid "Compute.api::inject_network_info %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:173
#, python-format
msgid "Compute.api::lock %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:189
#, python-format
msgid "Compute.api::unlock %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:219
#, python-format
msgid "createBackup entity requires %s attribute"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:223
msgid "Malformed createBackup entity"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:229
msgid "createBackup attribute 'rotation' must be an integer"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:244
#: cinder/api/openstack/compute/contrib/console_output.py:47
#: cinder/api/openstack/compute/contrib/console_output.py:59
#: cinder/api/openstack/compute/contrib/consoles.py:49
#: cinder/api/openstack/compute/contrib/consoles.py:60
#: cinder/api/openstack/compute/contrib/server_action_list.py:49
#: cinder/api/openstack/compute/contrib/server_diagnostics.py:47
#: cinder/api/openstack/compute/contrib/server_start_stop.py:38
msgid "Instance not found"
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:272
msgid "host and block_migration must be specified."
msgstr ""

#: cinder/api/openstack/compute/contrib/admin_actions.py:284
#, python-format
msgid "Live migration of instance %(id)s to host %(host)s failed"
msgstr ""

#: cinder/api/openstack/compute/contrib/aggregates.py:76
#, python-format
msgid ""
"Cannot create aggregate with name %(name)s and availability zone "
"%(avail_zone)s"
msgstr ""

#: cinder/api/openstack/compute/contrib/aggregates.py:88
#, python-format
msgid "Cannot show aggregate: %(id)s"
msgstr ""

#: cinder/api/openstack/compute/contrib/aggregates.py:114
#, python-format
msgid "Cannot update aggregate: %(id)s"
msgstr ""

#: cinder/api/openstack/compute/contrib/aggregates.py:126
#, python-format
msgid "Cannot delete aggregate: %(id)s"
msgstr ""

#: cinder/api/openstack/compute/contrib/aggregates.py:139
#, python-format
msgid "Aggregates does not have %s action"
msgstr ""

#: cinder/api/openstack/compute/contrib/aggregates.py:152
#: cinder/api/openstack/compute/contrib/aggregates.py:158
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s"
msgstr ""

#: cinder/api/openstack/compute/contrib/aggregates.py:171
#: cinder/api/openstack/compute/contrib/aggregates.py:175
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s"
msgstr ""

#: cinder/api/openstack/compute/contrib/aggregates.py:195
#, python-format
msgid "Cannot set metadata %(metadata)s in aggregate %(id)s"
msgstr ""

#: cinder/api/openstack/compute/contrib/certificates.py:75
msgid "Only root certificate can be retrieved."
msgstr ""

#: cinder/api/openstack/compute/contrib/cloudpipe.py:146
msgid ""
"Unable to claim IP for VPN instances, ensure it isn't running, and try "
"again in a few minutes"
msgstr ""

#: cinder/api/openstack/compute/contrib/consoles.py:44
msgid "Missing type specification"
msgstr ""

#: cinder/api/openstack/compute/contrib/consoles.py:56
msgid "Invalid type specification"
msgstr ""

#: cinder/api/openstack/compute/contrib/disk_config.py:44
#, python-format
msgid "%s must be either 'MANUAL' or 'AUTO'."
msgstr ""

#: cinder/api/openstack/compute/contrib/extended_server_attributes.py:77
#: cinder/api/openstack/compute/contrib/extended_status.py:61
msgid "Server not found."
msgstr ""

#: cinder/api/openstack/compute/contrib/flavorextradata.py:61
#: cinder/api/openstack/compute/contrib/flavorextradata.py:91
msgid "Flavor not found."
msgstr ""

#: cinder/api/openstack/compute/contrib/flavorextraspecs.py:49
#: cinder/api/openstack/compute/contrib/storagetypes.py:158
msgid "No Request Body"
msgstr ""

#: cinder/api/openstack/compute/contrib/floating_ips.py:159
#, python-format
msgid "No more floating ips in pool %s."
msgstr ""

#: cinder/api/openstack/compute/contrib/floating_ips.py:161
msgid "No more floating ips available."
msgstr ""

#: cinder/api/openstack/compute/contrib/floating_ips.py:201
#: cinder/api/openstack/compute/contrib/floating_ips.py:230
#: cinder/api/openstack/compute/contrib/security_groups.py:571
#: cinder/api/openstack/compute/contrib/security_groups.py:604
msgid "Missing parameter dict"
msgstr ""

#: cinder/api/openstack/compute/contrib/floating_ips.py:204
#: cinder/api/openstack/compute/contrib/floating_ips.py:233
msgid "Address not specified"
msgstr ""

#: cinder/api/openstack/compute/contrib/floating_ips.py:213
msgid "No fixed ips associated to instance"
msgstr ""

#: cinder/api/openstack/compute/contrib/floating_ips.py:216
msgid "Associate floating ip failed"
msgstr ""

#: cinder/api/openstack/compute/contrib/hosts.py:144
#, python-format
msgid "Invalid status: '%s'"
msgstr ""

#: cinder/api/openstack/compute/contrib/hosts.py:148
#, python-format
msgid "Invalid mode: '%s'"
msgstr ""

#: cinder/api/openstack/compute/contrib/hosts.py:152
#, python-format
msgid "Invalid update setting: '%s'"
msgstr ""

#: cinder/api/openstack/compute/contrib/hosts.py:170
#, python-format
msgid "Putting host %(host)s in maintenance mode %(mode)s."
msgstr ""

#: cinder/api/openstack/compute/contrib/hosts.py:181
#, python-format
msgid "Setting host %(host)s to %(state)s."
msgstr ""

#: cinder/api/openstack/compute/contrib/hosts.py:230
msgid "Describe-resource is admin only functionality"
msgstr ""

#: cinder/api/openstack/compute/contrib/hosts.py:238
msgid "Host not found"
msgstr ""

#: cinder/api/openstack/compute/contrib/keypairs.py:70
msgid "Keypair name contains unsafe characters"
msgstr ""

#: cinder/api/openstack/compute/contrib/keypairs.py:95
msgid "Keypair name must be between 1 and 255 characters long"
msgstr ""

#: cinder/api/openstack/compute/contrib/keypairs.py:100
#, python-format
msgid "Key pair '%s' already exists."
msgstr ""

#: cinder/api/openstack/compute/contrib/multinic.py:52
msgid "Missing 'networkId' argument for addFixedIp"
msgstr ""

#: cinder/api/openstack/compute/contrib/multinic.py:68
msgid "Missing 'address' argument for removeFixedIp"
msgstr ""

#: cinder/api/openstack/compute/contrib/multinic.py:77
#, python-format
msgid "Unable to find address %r"
msgstr ""

#: cinder/api/openstack/compute/contrib/networks.py:62
#, python-format
msgid "Network does not have %s action"
msgstr ""

#: cinder/api/openstack/compute/contrib/networks.py:70
#, python-format
msgid "Disassociating network with id %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/networks.py:74
#: cinder/api/openstack/compute/contrib/networks.py:91
#: cinder/api/openstack/compute/contrib/networks.py:101
msgid "Network not found"
msgstr ""

#: cinder/api/openstack/compute/contrib/networks.py:87
#, python-format
msgid "Showing network with id %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/networks.py:97
#, python-format
msgid "Deleting network with id %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/scheduler_hints.py:41
msgid "Malformed scheduler_hints attribute"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:222
msgid "Security group id should be integer"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:243
msgid "Security group is still in use"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:295
#, python-format
msgid "Security group %s already exists"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:315
#, python-format
msgid "Security group %s is not a string or unicode"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:318
#, python-format
msgid "Security group %s cannot be empty."
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:321
#, python-format
msgid "Security group %s should not be greater than 255 characters."
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:348
msgid "Parent group id is not integer"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:351
#, python-format
msgid "Security group (%s) not found"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:369
msgid "Not enough parameters to build a valid rule."
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:376
#, python-format
msgid "This rule already exists in group %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:414
msgid "Parent or group id is not integer"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:507
msgid "Rule id is not integer"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:510
#, python-format
msgid "Rule (%s) not found"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:574
#: cinder/api/openstack/compute/contrib/security_groups.py:607
msgid "Security group not specified"
msgstr ""

#: cinder/api/openstack/compute/contrib/security_groups.py:578
#: cinder/api/openstack/compute/contrib/security_groups.py:611
msgid "Security group name cannot be empty"
msgstr ""

#: cinder/api/openstack/compute/contrib/server_start_stop.py:45
#, python-format
msgid "start instance %r"
msgstr ""

#: cinder/api/openstack/compute/contrib/server_start_stop.py:54
#, python-format
msgid "stop instance %r"
msgstr ""

#: cinder/api/openstack/compute/contrib/storages.py:73
#: cinder/api/openstack/storage/storages.py:106
#, python-format
msgid "vol=%s"
msgstr ""

#: cinder/api/openstack/compute/contrib/storages.py:146
#: cinder/api/openstack/storage/storages.py:184
#, python-format
msgid "Delete storage with id: %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/storages.py:329
#, python-format
msgid "Attach storage %(storage_id)s to instance %(server_id)s at %(device)s"
msgstr ""

#: cinder/api/openstack/compute/contrib/storages.py:481
#: cinder/api/openstack/storage/snapshots.py:110
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: cinder/api/openstack/compute/contrib/storages.py:524
#: cinder/api/openstack/storage/snapshots.py:150
#, python-format
msgid "Create snapshot from storage %s"
msgstr ""

#: cinder/auth/fakeldap.py:33
msgid "Attempted to instantiate singleton"
msgstr ""

#: cinder/auth/ldapdriver.py:650
#, python-format
msgid ""
"Attempted to remove the last member of a group. Deleting the group at %s "
"instead."
msgstr ""

#: cinder/auth/manager.py:298
#, python-format
msgid "Looking up user: %r"
msgstr ""

#: cinder/auth/manager.py:302
#, python-format
msgid "Failed authorization for access key %s"
msgstr ""

#: cinder/auth/manager.py:308
#, python-format
msgid "Using project name = user name (%s)"
msgstr ""

#: cinder/auth/manager.py:315
#, python-format
msgid "failed authorization: no project named %(pjid)s (user=%(uname)s)"
msgstr ""

#: cinder/auth/manager.py:324
#, python-format
msgid ""
"Failed authorization: user %(uname)s not admin and not member of project "
"%(pjname)s"
msgstr ""

#: cinder/auth/manager.py:331 cinder/auth/manager.py:343
#, python-format
msgid "user.secret: %s"
msgstr ""

#: cinder/auth/manager.py:332 cinder/auth/manager.py:344
#, python-format
msgid "expected_signature: %s"
msgstr ""

#: cinder/auth/manager.py:333 cinder/auth/manager.py:345
#, python-format
msgid "signature: %s"
msgstr ""

#: cinder/auth/manager.py:335 cinder/auth/manager.py:357
#, python-format
msgid "Invalid signature for user %s"
msgstr ""

#: cinder/auth/manager.py:353
#, python-format
msgid "host_only_signature: %s"
msgstr ""

#: cinder/auth/manager.py:449
msgid "Must specify project"
msgstr ""

#: cinder/auth/manager.py:490
#, python-format
msgid "Adding role %(role)s to user %(uid)s in project %(pid)s"
msgstr ""

#: cinder/auth/manager.py:493
#, python-format
msgid "Adding sitewide role %(role)s to user %(uid)s"
msgstr ""

#: cinder/auth/manager.py:519
#, python-format
msgid "Removing role %(role)s from user %(uid)s on project %(pid)s"
msgstr ""

#: cinder/auth/manager.py:522
#, python-format
msgid "Removing sitewide role %(role)s from user %(uid)s"
msgstr ""

#: cinder/auth/manager.py:595
#, python-format
msgid "Created project %(name)s with manager %(manager_user)s"
msgstr ""

#: cinder/auth/manager.py:613
#, python-format
msgid "modifying project %s"
msgstr ""

#: cinder/auth/manager.py:625
#, python-format
msgid "Adding user %(uid)s to project %(pid)s"
msgstr ""

#: cinder/auth/manager.py:646
#, python-format
msgid "Remove user %(uid)s from project %(pid)s"
msgstr ""

#: cinder/auth/manager.py:676
#, python-format
msgid "Deleting project %s"
msgstr ""

#: cinder/auth/manager.py:734
#, python-format
msgid "Created user %(rvname)s (admin: %(rvadmin)r)"
msgstr ""

#: cinder/auth/manager.py:743
#, python-format
msgid "Deleting user %s"
msgstr ""

#: cinder/auth/manager.py:753
#, python-format
msgid "Access Key change for user %s"
msgstr ""

#: cinder/auth/manager.py:755
#, python-format
msgid "Secret Key change for user %s"
msgstr ""

#: cinder/auth/manager.py:757
#, python-format
msgid "Admin status set to %(admin)r for user %(uid)s"
msgstr ""

#: cinder/auth/manager.py:802
#, python-format
msgid "No vpn data for project %s"
msgstr ""

#: cinder/cloudpipe/pipelib.py:46
msgid "Instance type for vpn instances"
msgstr ""

#: cinder/cloudpipe/pipelib.py:49
msgid "Template for cloudpipe instance boot script"
msgstr ""

#: cinder/cloudpipe/pipelib.py:52
msgid "Network to push into openvpn config"
msgstr ""

#: cinder/cloudpipe/pipelib.py:55
msgid "Netmask to push into openvpn config"
msgstr ""

#: cinder/cloudpipe/pipelib.py:107
#, python-format
msgid "Launching VPN for %s"
msgstr ""

#: cinder/compute/api.py:141
msgid "No compute host specified"
msgstr ""

#: cinder/compute/api.py:144
#, python-format
msgid "Unable to find host for Instance %s"
msgstr ""

#: cinder/compute/api.py:192
#, python-format
msgid ""
"Quota exceeded for %(pid)s, tried to set %(num_metadata)s metadata "
"properties"
msgstr ""

#: cinder/compute/api.py:203
#, python-format
msgid "Quota exceeded for %(pid)s, metadata property key or value too long"
msgstr ""

#: cinder/compute/api.py:257
msgid "Cannot run any more instances of this type."
msgstr ""

#: cinder/compute/api.py:259
#, python-format
msgid "Can only run %s more instances of this type."
msgstr ""

#: cinder/compute/api.py:261
#, python-format
msgid "Quota exceeded for %(pid)s, tried to run %(min_count)s instances. "
msgstr ""

#: cinder/compute/api.py:310
msgid "Creating a raw instance"
msgstr ""

#: cinder/compute/api.py:312
#, python-format
msgid "Using Kernel=%(kernel_id)s, Ramdisk=%(ramdisk_id)s"
msgstr ""

#: cinder/compute/api.py:383
#, python-format
msgid "Going to run %s instances..."
msgstr ""

#: cinder/compute/api.py:447
#, python-format
msgid "bdm %s"
msgstr ""

#: cinder/compute/api.py:474
#, python-format
msgid "block_device_mapping %s"
msgstr ""

#: cinder/compute/api.py:591
#, python-format
msgid "Sending create to scheduler for %(pid)s/%(uid)s's"
msgstr ""

#: cinder/compute/api.py:871
msgid "Going to try to soft delete instance"
msgstr ""

#: cinder/compute/api.py:891
msgid "No host for instance, deleting immediately"
msgstr ""

#: cinder/compute/api.py:939
msgid "Going to try to terminate instance"
msgstr ""

#: cinder/compute/api.py:977
msgid "Going to try to stop instance"
msgstr ""

#: cinder/compute/api.py:996
msgid "Going to try to start instance"
msgstr ""

#: cinder/compute/api.py:1000
#, python-format
msgid "Instance %(instance_uuid)s is not stopped. (%(vm_state)s"
msgstr ""

#: cinder/compute/api.py:1071 cinder/storage/api.py:173
#: cinder/storage/storage_types.py:64
#, python-format
msgid "Searching by: %s"
msgstr ""

#: cinder/compute/api.py:1201
#, python-format
msgid "Image type not recognized %s"
msgstr ""

#: cinder/compute/api.py:1369
msgid "flavor_id is None. Assuming migration."
msgstr ""

#: cinder/compute/api.py:1377
#, python-format
msgid ""
"Old instance type %(current_instance_type_name)s,  new instance type "
"%(new_instance_type_name)s"
msgstr ""

#: cinder/compute/api.py:1644
#, python-format
msgid "multiple fixedips exist, using the first: %s"
msgstr ""

#: cinder/compute/instance_types.py:57 cinder/compute/instance_types.py:65
msgid "create arguments must be positive integers"
msgstr ""

#: cinder/compute/instance_types.py:76 cinder/storage/storage_types.py:41
#, python-format
msgid "DB error: %s"
msgstr ""

#: cinder/compute/instance_types.py:86
#, python-format
msgid "Instance type %s not found for deletion"
msgstr ""

#: cinder/compute/manager.py:138
#, python-format
msgid "check_instance_lock: decorating: |%s|"
msgstr ""

#: cinder/compute/manager.py:140
#, python-format
msgid ""
"check_instance_lock: arguments: |%(self)s| |%(context)s| "
"|%(instance_uuid)s|"
msgstr ""

#: cinder/compute/manager.py:144
#, python-format
msgid "check_instance_lock: locked: |%s|"
msgstr ""

#: cinder/compute/manager.py:146
#, python-format
msgid "check_instance_lock: admin: |%s|"
msgstr ""

#: cinder/compute/manager.py:151
#, python-format
msgid "check_instance_lock: executing: |%s|"
msgstr ""

#: cinder/compute/manager.py:155
#, python-format
msgid "check_instance_lock: not executing |%s|"
msgstr ""

#: cinder/compute/manager.py:201
#, python-format
msgid "Unable to load the virtualization driver: %s"
msgstr ""

#: cinder/compute/manager.py:223
#, python-format
msgid ""
"Instance %(instance_uuid)s has been destroyed from under us while trying "
"to set it to ERROR"
msgstr ""

#: cinder/compute/manager.py:240
#, python-format
msgid "Current state is %(drv_state)s, state in DB is %(db_state)s."
msgstr ""

#: cinder/compute/manager.py:245
msgid "Rebooting instance after cinder-compute restart."
msgstr ""

#: cinder/compute/manager.py:255
msgid "Hypervisor driver does not support firewall rules"
msgstr ""

#: cinder/compute/manager.py:260
msgid "Checking state"
msgstr ""

#: cinder/compute/manager.py:329
#, python-format
msgid "Setting up bdm %s"
msgstr ""

#: cinder/compute/manager.py:400
#, python-format
msgid "Instance %s already deleted from database. Attempting forceful vm deletion"
msgstr ""

#: cinder/compute/manager.py:406
#, python-format
msgid "Exception encountered while terminating the instance %s"
msgstr ""

#: cinder/compute/manager.py:444
#, python-format
msgid "Instance %s not found."
msgstr ""

#: cinder/compute/manager.py:480
msgid "Instance has already been created"
msgstr ""

#: cinder/compute/manager.py:523
#, python-format
msgid ""
"image_id=%(image_id)s, image_size_bytes=%(size_bytes)d, "
"allowed_size_bytes=%(allowed_size_bytes)d"
msgstr ""

#: cinder/compute/manager.py:528
#, python-format
msgid ""
"Image '%(image_id)s' size %(size_bytes)d exceeded instance_type allowed "
"size %(allowed_size_bytes)d"
msgstr ""

#: cinder/compute/manager.py:538
msgid "Starting instance..."
msgstr ""

#: cinder/compute/manager.py:548
msgid "Skipping network allocation for instance"
msgstr ""

#: cinder/compute/manager.py:561
msgid "Instance failed network setup"
msgstr ""

#: cinder/compute/manager.py:565
#, python-format
msgid "Instance network_info: |%s|"
msgstr ""

#: cinder/compute/manager.py:578
msgid "Instance failed block device setup"
msgstr ""

#: cinder/compute/manager.py:594
msgid "Instance failed to spawn"
msgstr ""

#: cinder/compute/manager.py:615
msgid "Deallocating network for instance"
msgstr ""

#: cinder/compute/manager.py:672
#, python-format
msgid "%(action_str)s instance"
msgstr ""

#: cinder/compute/manager.py:699
#, python-format
msgid "Ignoring DiskNotFound: %s"
msgstr ""

#: cinder/compute/manager.py:708
#, python-format
msgid "terminating bdm %s"
msgstr ""

#: cinder/compute/manager.py:742 cinder/compute/manager.py:1328
#: cinder/compute/manager.py:1416 cinder/compute/manager.py:2501
#, python-format
msgid "%s. Setting instance vm_state to ERROR"
msgstr ""

#: cinder/compute/manager.py:811
#, python-format
msgid ""
"Cannot rebuild instance [%(instance_uuid)s], because the given image does"
" not exist."
msgstr ""

#: cinder/compute/manager.py:816
#, python-format
msgid "Cannot rebuild instance [%(instance_uuid)s]: %(exc)s"
msgstr ""

#: cinder/compute/manager.py:823
#, python-format
msgid "Rebuilding instance %s"
msgstr ""

#: cinder/compute/manager.py:876
#, python-format
msgid "Rebooting instance %s"
msgstr ""

#: cinder/compute/manager.py:891
#, python-format
msgid ""
"trying to reboot a non-running instance: %(instance_uuid)s (state: "
"%(state)s expected: %(running)s)"
msgstr ""

#: cinder/compute/manager.py:933
#, python-format
msgid "instance %s: snapshotting"
msgstr ""

#: cinder/compute/manager.py:939
#, python-format
msgid ""
"trying to snapshot a non-running instance: %(instance_uuid)s (state: "
"%(state)s expected: %(running)s)"
msgstr ""

#: cinder/compute/manager.py:995
#, python-format
msgid "Found %(num_images)d images (rotation: %(rotation)d)"
msgstr ""

#: cinder/compute/manager.py:1001
#, python-format
msgid "Rotating out %d backups"
msgstr ""

#: cinder/compute/manager.py:1005
#, python-format
msgid "Deleting image %s"
msgstr ""

#: cinder/compute/manager.py:1035
#, python-format
msgid "Failed to set admin password. Instance %s is not running"
msgstr ""

#: cinder/compute/manager.py:1041
#, python-format
msgid "Instance %s: Root password set"
msgstr ""

#: cinder/compute/manager.py:1050
msgid "set_admin_password is not implemented by this driver."
msgstr ""

#: cinder/compute/manager.py:1064
msgid "Error setting admin password"
msgstr ""

#: cinder/compute/manager.py:1079
#, python-format
msgid ""
"trying to inject a file into a non-running instance: %(instance_uuid)s "
"(state: %(current_power_state)s expected: %(expected_state)s)"
msgstr ""

#: cinder/compute/manager.py:1084
#, python-format
msgid "instance %(instance_uuid)s: injecting file to %(path)s"
msgstr ""

#: cinder/compute/manager.py:1098
#, python-format
msgid ""
"trying to update agent on a non-running instance: %(instance_uuid)s "
"(state: %(current_power_state)s expected: %(expected_state)s)"
msgstr ""

#: cinder/compute/manager.py:1103
#, python-format
msgid "instance %(instance_uuid)s: updating agent to %(url)s"
msgstr ""

#: cinder/compute/manager.py:1116
#, python-format
msgid "instance %s: rescuing"
msgstr ""

#: cinder/compute/manager.py:1141
#, python-format
msgid "instance %s: unrescuing"
msgstr ""

#: cinder/compute/manager.py:1270
msgid "destination same as source!"
msgstr ""

#: cinder/compute/manager.py:1287
#, python-format
msgid "instance %s: migrating"
msgstr ""

#: cinder/compute/manager.py:1471
#, python-format
msgid "instance %s: pausing"
msgstr ""

#: cinder/compute/manager.py:1489
#, python-format
msgid "instance %s: unpausing"
msgstr ""

#: cinder/compute/manager.py:1525
#, python-format
msgid "instance %s: retrieving diagnostics"
msgstr ""

#: cinder/compute/manager.py:1534
#, python-format
msgid "instance %s: suspending"
msgstr ""

#: cinder/compute/manager.py:1556
#, python-format
msgid "instance %s: resuming"
msgstr ""

#: cinder/compute/manager.py:1579
#, python-format
msgid "instance %s: locking"
msgstr ""

#: cinder/compute/manager.py:1588
#, python-format
msgid "instance %s: unlocking"
msgstr ""

#: cinder/compute/manager.py:1596
#, python-format
msgid "instance %s: getting locked state"
msgstr ""

#: cinder/compute/manager.py:1606
#, python-format
msgid "instance %s: reset network"
msgstr ""

#: cinder/compute/manager.py:1614
#, python-format
msgid "instance %s: inject network info"
msgstr ""

#: cinder/compute/manager.py:1618
#, python-format
msgid "network_info to inject: |%s|"
msgstr ""

#: cinder/compute/manager.py:1655
#, python-format
msgid "instance %s: getting vnc console"
msgstr ""

#: cinder/compute/manager.py:1685
#, python-format
msgid "Booting with storage %(storage_id)s at %(mountpoint)s"
msgstr ""

#: cinder/compute/manager.py:1703
#, python-format
msgid ""
"instance %(instance_uuid)s: attaching storage %(storage_id)s to "
"%(mountpoint)s"
msgstr ""

#: cinder/compute/manager.py:1705
#, python-format
msgid "Attaching storage %(storage_id)s to %(mountpoint)s"
msgstr ""

#: cinder/compute/manager.py:1714
#, python-format
msgid "instance %(instance_uuid)s: attach failed %(mountpoint)s, removing"
msgstr ""

#: cinder/compute/manager.py:1724
#, python-format
msgid "Attach failed %(mountpoint)s, removing"
msgstr ""

#: cinder/compute/manager.py:1752
#, python-format
msgid "Detach storage %(storage_id)s from mountpoint %(mp)s"
msgstr ""

#: cinder/compute/manager.py:1756
#, python-format
msgid "Detaching storage from unknown instance %s"
msgstr ""

#: cinder/compute/manager.py:1822
#, python-format
msgid ""
"Creating tmpfile %s to notify to other compute nodes that they should "
"mount the same storage."
msgstr ""

#: cinder/compute/manager.py:1884
msgid "Instance has no storage."
msgstr ""

#: cinder/compute/manager.py:1916
#, python-format
msgid "plug_vifs() failed %(cnt)d.Retry up to %(max_retry)d for %(hostname)s."
msgstr ""

#: cinder/compute/manager.py:1973
#, python-format
msgid "Pre live migration failed at  %(dest)s"
msgstr ""

#: cinder/compute/manager.py:2000
msgid "post_live_migration() is started.."
msgstr ""

#: cinder/compute/manager.py:2030
msgid "No floating_ip found"
msgstr ""

#: cinder/compute/manager.py:2038
msgid "No floating_ip found."
msgstr ""

#: cinder/compute/manager.py:2040
#, python-format
msgid ""
"Live migration: Unexpected error: cannot inherit floating ip.\n"
"%(e)s"
msgstr ""

#: cinder/compute/manager.py:2073
#, python-format
msgid "Migrating instance to %(dest)s finished successfully."
msgstr ""

#: cinder/compute/manager.py:2075
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""

#: cinder/compute/manager.py:2090
msgid "Post operation of migration started"
msgstr ""

#: cinder/compute/manager.py:2226
#, python-format
msgid "Updated the info_cache for instance %s"
msgstr ""

#: cinder/compute/manager.py:2255
msgid "Updating bandwidth usage cache"
msgstr ""

#: cinder/compute/manager.py:2277
msgid "Updating host status"
msgstr ""

#: cinder/compute/manager.py:2305
#, python-format
msgid ""
"Found %(num_db_instances)s in the database and %(num_vm_instances)s on "
"the hypervisor."
msgstr ""

#: cinder/compute/manager.py:2331
#, python-format
msgid ""
"During the sync_power process the instance %(uuid)s has moved from host "
"%(src)s to host %(dst)s"
msgstr ""

#: cinder/compute/manager.py:2344
#, python-format
msgid ""
"Instance %s is in the process of migrating to this host. Wait next "
"sync_power cycle before setting power state to NOSTATE"
msgstr ""

#: cinder/compute/manager.py:2350
msgid ""
"Instance found in database but not known by hypervisor. Setting power "
"state to NOSTATE"
msgstr ""

#: cinder/compute/manager.py:2380
msgid "FLAGS.reclaim_instance_interval <= 0, skipping..."
msgstr ""

#: cinder/compute/manager.py:2392
msgid "Reclaiming deleted instance"
msgstr ""

#: cinder/compute/manager.py:2458
#, python-format
msgid ""
"Detected instance with name label '%(name)s' which is marked as DELETED "
"but still present on host."
msgstr ""

#: cinder/compute/manager.py:2465
#, python-format
msgid ""
"Destroying instance with name label '%(name)s' which is marked as DELETED"
" but still present on host."
msgstr ""

#: cinder/compute/manager.py:2472
#, python-format
msgid "Unrecognized value '%(action)s' for FLAGS.running_deleted_instance_action"
msgstr ""

#: cinder/compute/manager.py:2542
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: unrecoverable state during operation on "
"%(host)s"
msgstr ""

#: cinder/compute/utils.py:142
msgid "v4 subnets are required for legacy nw_info"
msgstr ""

#: cinder/console/manager.py:77 cinder/console/vmrc_manager.py:70
msgid "Adding console"
msgstr ""

#: cinder/console/manager.py:97
#, python-format
msgid "Tried to remove non-existent console %(console_id)s."
msgstr ""

#: cinder/console/vmrc_manager.py:122
#, python-format
msgid "Tried to remove non-existent console %(console_id)s."
msgstr ""

#: cinder/console/vmrc_manager.py:125
#, python-format
msgid "Removing console %(console_id)s."
msgstr ""

#: cinder/console/xvp.py:98
msgid "Rebuilding xvp conf"
msgstr ""

#: cinder/console/xvp.py:116
#, python-format
msgid "Re-wrote %s"
msgstr ""

#: cinder/console/xvp.py:121
msgid "Stopping xvp"
msgstr ""

#: cinder/console/xvp.py:134
msgid "Starting xvp"
msgstr ""

#: cinder/console/xvp.py:141
#, python-format
msgid "Error starting xvp: %s"
msgstr ""

#: cinder/console/xvp.py:144
msgid "Restarting xvp"
msgstr ""

#: cinder/console/xvp.py:146
msgid "xvp not running..."
msgstr ""

#: cinder/consoleauth/manager.py:63
#, python-format
msgid "Deleting Expired Token: (%s)"
msgstr ""

#: cinder/consoleauth/manager.py:75
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s)"
msgstr ""

#: cinder/consoleauth/manager.py:79
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s)"
msgstr ""

#: cinder/db/sqlalchemy/api.py:57
msgid "Use of empty request context is deprecated"
msgstr ""

#: cinder/db/sqlalchemy/api.py:198
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: cinder/db/sqlalchemy/api.py:516 cinder/db/sqlalchemy/api.py:551
#, python-format
msgid "No ComputeNode for %(host)s"
msgstr ""

#: cinder/db/sqlalchemy/api.py:4019 cinder/db/sqlalchemy/api.py:4045
#, python-format
msgid "No backend config with id %(sm_backend_id)s"
msgstr ""

#: cinder/db/sqlalchemy/api.py:4103
#, python-format
msgid "No sm_flavor called %(sm_flavor)s"
msgstr ""

#: cinder/db/sqlalchemy/api.py:4147
#, python-format
msgid "No sm_storage with id %(storage_id)s"
msgstr ""

#: cinder/db/sqlalchemy/migration.py:66
msgid "python-migrate is not installed. Exiting."
msgstr ""

#: cinder/db/sqlalchemy/migration.py:78
msgid "version should be an integer"
msgstr ""

#: cinder/db/sqlalchemy/session.py:137
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/030_multi_nic.py:48
msgid "interface column not added to networks table"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/030_multi_nic.py:80
#: cinder/db/sqlalchemy/migrate_repo/versions/062_add_instance_info_cache_table.py:54
#: cinder/db/sqlalchemy/migrate_repo/versions/072_add_dns_table.py:61
#: cinder/db/sqlalchemy/migrate_repo/versions/083_quota_class.py:48
#, python-format
msgid "Table |%s| not created!"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/030_multi_nic.py:87
msgid "VIF column not added to fixed_ips table"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/030_multi_nic.py:97
#, python-format
msgid "join list for moving mac_addresses |%s|"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/031_fk_fixed_ips_virtual_interface_id.py:39
#: cinder/db/sqlalchemy/migrate_repo/versions/047_remove_instances_fk_from_vif.py:60
#: cinder/db/sqlalchemy/migrate_repo/versions/060_remove_network_fk_from_vif.py:61
#: cinder/db/sqlalchemy/migrate_repo/versions/070_untie_cinder_network_models.py:99
msgid "foreign key constraint couldn't be added"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/031_fk_fixed_ips_virtual_interface_id.py:58
msgid "foreign key constraint couldn't be dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/045_add_network_priority.py:34
msgid "priority column not added to networks table"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/047_remove_instances_fk_from_vif.py:41
#: cinder/db/sqlalchemy/migrate_repo/versions/060_remove_network_fk_from_vif.py:42
#: cinder/db/sqlalchemy/migrate_repo/versions/064_change_instance_id_to_uuid_in_instance_actions.py:56
#: cinder/db/sqlalchemy/migrate_repo/versions/070_untie_cinder_network_models.py:68
msgid "foreign key constraint couldn't be removed"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/049_add_instances_progress.py:34
msgid "progress column not added to instances table"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/055_convert_flavor_id_to_str.py:97
#, python-format
msgid ""
"Could not cast flavorid to integer: %s. Set flavorid to an integer-like "
"string to downgrade."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/062_add_instance_info_cache_table.py:69
msgid "instance_info_caches tables not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/069_block_migration.py:41
msgid "progress column not added to compute_nodes table"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/072_add_dns_table.py:76
msgid "dns_domains table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/083_quota_class.py:60
msgid "quota_classes table not dropped"
msgstr ""

#: cinder/image/glance.py:147
msgid "Connection error contacting glance server, retrying"
msgstr ""

#: cinder/image/glance.py:153 cinder/network/quantum/melange_connection.py:104
msgid "Maximum attempts reached"
msgstr ""

#: cinder/image/glance.py:278
#, python-format
msgid "Creating image in Glance. Metadata passed in %s"
msgstr ""

#: cinder/image/glance.py:281
#, python-format
msgid "Metadata after formatting for Glance %s"
msgstr ""

#: cinder/image/glance.py:289
#, python-format
msgid "Metadata returned from Glance formatted for Base %s"
msgstr ""

#: cinder/image/glance.py:331 cinder/image/glance.py:335
msgid "Not the image owner"
msgstr ""

#: cinder/image/glance.py:410
#, python-format
msgid "%(timestamp)s does not follow any of the signatures: %(iso_formats)s"
msgstr ""

#: cinder/image/s3.py:309
#, python-format
msgid "Failed to download %(image_location)s to %(image_path)s"
msgstr ""

#: cinder/image/s3.py:328
#, python-format
msgid "Failed to decrypt %(image_location)s to %(image_path)s"
msgstr ""

#: cinder/image/s3.py:340
#, python-format
msgid "Failed to untar %(image_location)s to %(image_path)s"
msgstr ""

#: cinder/image/s3.py:353
#, python-format
msgid "Failed to upload %(image_location)s to %(image_path)s"
msgstr ""

#: cinder/image/s3.py:379
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr ""

#: cinder/image/s3.py:387
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr ""

#: cinder/image/s3.py:398
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr ""

#: cinder/image/s3.py:410
msgid "Unsafe filenames in image"
msgstr ""

#: cinder/ipv6/account_identifier.py:38 cinder/ipv6/rfc2462.py:34
#, python-format
msgid "Bad mac for to_global_ipv6: %s"
msgstr ""

#: cinder/ipv6/account_identifier.py:40 cinder/ipv6/rfc2462.py:36
#, python-format
msgid "Bad prefix for to_global_ipv6: %s"
msgstr ""

#: cinder/ipv6/account_identifier.py:42
#, python-format
msgid "Bad project_id for to_global_ipv6: %s"
msgstr ""

#: cinder/network/ldapdns.py:321
msgid "This driver only supports type 'a' entries."
msgstr ""

#: cinder/network/linux_net.py:166
#, python-format
msgid "Attempted to remove chain %s which does not exist"
msgstr ""

#: cinder/network/linux_net.py:192
#, python-format
msgid "Unknown chain: %r"
msgstr ""

#: cinder/network/linux_net.py:215
#, python-format
msgid ""
"Tried to remove rule that was not there: %(chain)r %(rule)r %(wrap)r "
"%(top)r"
msgstr ""

#: cinder/network/linux_net.py:335
msgid "IPTablesManager.apply completed with success"
msgstr ""

#: cinder/network/linux_net.py:694
#, python-format
msgid "Hupping dnsmasq threw %s"
msgstr ""

#: cinder/network/linux_net.py:696
#, python-format
msgid "Pid %d is stale, relaunching dnsmasq"
msgstr ""

#: cinder/network/linux_net.py:756
#, python-format
msgid "killing radvd threw %s"
msgstr ""

#: cinder/network/linux_net.py:758
#, python-format
msgid "Pid %d is stale, relaunching radvd"
msgstr ""

#: cinder/network/linux_net.py:967
#, python-format
msgid "Starting VLAN inteface %s"
msgstr ""

#: cinder/network/linux_net.py:999
#, python-format
msgid "Starting Bridge interface for %s"
msgstr ""

#: cinder/network/linux_net.py:1142
#, python-format
msgid "Starting bridge %s "
msgstr ""

#: cinder/network/linux_net.py:1149
#, python-format
msgid "Done starting bridge %s"
msgstr ""

#: cinder/network/linux_net.py:1167
#, python-format
msgid "Failed unplugging gateway interface '%s'"
msgstr ""

#: cinder/network/linux_net.py:1170
#, python-format
msgid "Unplugged gateway interface '%s'"
msgstr ""

#: cinder/network/manager.py:291
#, python-format
msgid "Fixed ip %(fixed_ip_id)s not found"
msgstr ""

#: cinder/network/manager.py:300 cinder/network/manager.py:496
#, python-format
msgid "Interface %(interface)s not found"
msgstr ""

#: cinder/network/manager.py:315
#, python-format
msgid "floating IP allocation for instance |%s|"
msgstr ""

#: cinder/network/manager.py:353
#, python-format
msgid "floating IP deallocation for instance |%s|"
msgstr ""

#: cinder/network/manager.py:386
#, python-format
msgid "Address |%(address)s| is not allocated"
msgstr ""

#: cinder/network/manager.py:390
#, python-format
msgid "Address |%(address)s| is not allocated to your project |%(project)s|"
msgstr ""

#: cinder/network/manager.py:402
#, python-format
msgid "Quota exceeded for %s, tried to allocate address"
msgstr ""

#: cinder/network/manager.py:614
#, python-format
msgid ""
"Database inconsistency: DNS domain |%s| is registered in the Vsm db but "
"not visible to either the floating or instance DNS driver. It will be "
"ignored."
msgstr ""

#: cinder/network/manager.py:660
#, python-format
msgid "Domain |%(domain)s| already exists, changing zone to |%(av_zone)s|."
msgstr ""

#: cinder/network/manager.py:670
#, python-format
msgid "Domain |%(domain)s| already exists, changing project to |%(project)s|."
msgstr ""

#: cinder/network/manager.py:778
#, python-format
msgid "Disassociated %s stale fixed ip(s)"
msgstr ""

#: cinder/network/manager.py:782
msgid "setting network host"
msgstr ""

#: cinder/network/manager.py:896
#, python-format
msgid "network allocations for instance |%s|"
msgstr ""

#: cinder/network/manager.py:901
#, python-format
msgid "networks retrieved for instance |%(instance_id)s|: |%(networks)s|"
msgstr ""

#: cinder/network/manager.py:930
#, python-format
msgid "network deallocation for instance |%s|"
msgstr ""

#: cinder/network/manager.py:1152
#, python-format
msgid ""
"instance-dns-zone is |%(domain)s|, which is in availability zone "
"|%(zone)s|. Instance |%(instance)s| is in zone |%(zone2)s|. No DNS record"
" will be created."
msgstr ""

#: cinder/network/manager.py:1227
#, python-format
msgid "Unable to release %s because vif doesn't exist."
msgstr ""

#: cinder/network/manager.py:1244
#, python-format
msgid "Leased IP |%(address)s|"
msgstr ""

#: cinder/network/manager.py:1248
#, python-format
msgid "IP %s leased that is not associated"
msgstr ""

#: cinder/network/manager.py:1256
#, python-format
msgid "IP |%s| leased that isn't allocated"
msgstr ""

#: cinder/network/manager.py:1261
#, python-format
msgid "Released IP |%(address)s|"
msgstr ""

#: cinder/network/manager.py:1265
#, python-format
msgid "IP %s released that is not associated"
msgstr ""

#: cinder/network/manager.py:1268
#, python-format
msgid "IP %s released that was not leased"
msgstr ""

#: cinder/network/manager.py:1331
msgid "cidr already in use"
msgstr ""

#: cinder/network/manager.py:1334
#, python-format
msgid "requested cidr (%(cidr)s) conflicts with existing supernet (%(super)s)"
msgstr ""

#: cinder/network/manager.py:1345
#, python-format
msgid ""
"requested cidr (%(cidr)s) conflicts with existing smaller cidr "
"(%(smaller)s)"
msgstr ""

#: cinder/network/manager.py:1404
msgid "Network already exists!"
msgstr ""

#: cinder/network/manager.py:1423
#, python-format
msgid "Network must be disassociated from project %s before delete"
msgstr ""

#: cinder/network/manager.py:1832
msgid ""
"The sum between the number of networks and the vlan start cannot be "
"greater than 4094"
msgstr ""

#: cinder/network/manager.py:1839
#, python-format
msgid ""
"The network range is not big enough to fit %(num_networks)s. Network size"
" is %(network_size)s"
msgstr ""

#: cinder/network/minidns.py:65
msgid "This driver only supports type 'a'"
msgstr ""

#: cinder/network/quantum/client.py:154
msgid "Tenant ID not set"
msgstr ""

#: cinder/network/quantum/client.py:180
#, python-format
msgid "Quantum Client Request: %(method)s %(action)s"
msgstr ""

#: cinder/network/quantum/client.py:196
#, python-format
msgid "Quantum entity not found: %s"
msgstr ""

#: cinder/network/quantum/client.py:206
#, python-format
msgid "Server %(status_code)s error: %(data)s"
msgstr ""

#: cinder/network/quantum/client.py:210
#, python-format
msgid "Unable to connect to server. Got error: %s"
msgstr ""

#: cinder/network/quantum/client.py:228
#, python-format
msgid "unable to deserialize object of type = '%s'"
msgstr ""

#: cinder/network/quantum/manager.py:162
msgid "QuantumManager does not use 'multi_host' parameter."
msgstr ""

#: cinder/network/quantum/manager.py:166
msgid "QuantumManager requires that only one network is created per call"
msgstr ""

#: cinder/network/quantum/manager.py:176
msgid "QuantumManager does not use 'vlan_start' parameter."
msgstr ""

#: cinder/network/quantum/manager.py:182
msgid "QuantumManager does not use 'vpn_start' parameter."
msgstr ""

#: cinder/network/quantum/manager.py:186
msgid "QuantumManager does not use 'bridge' parameter."
msgstr ""

#: cinder/network/quantum/manager.py:190
msgid "QuantumManager does not use 'bridge_interface' parameter."
msgstr ""

#: cinder/network/quantum/manager.py:195
msgid "QuantumManager requires a valid (.1) gateway address."
msgstr ""

#: cinder/network/quantum/manager.py:204
#, python-format
msgid ""
"Unable to find existing quantum network for tenant '%(q_tenant_id)s' with"
" net-id '%(quantum_net_id)s'"
msgstr ""

#: cinder/network/quantum/manager.py:301
#, python-format
msgid "network allocations for instance %s"
msgstr ""

#: cinder/network/quantum/manager.py:588
#, python-format
msgid ""
"port deallocation failed for instance: |%(instance_id)s|, port_id: "
"|%(port_id)s|"
msgstr ""

#: cinder/network/quantum/manager.py:606
#, python-format
msgid ""
"ipam deallocation failed for instance: |%(instance_id)s|, vif_uuid: "
"|%(vif_uuid)s|"
msgstr ""

#: cinder/network/quantum/melange_connection.py:96
#, python-format
msgid "Server returned error: %s"
msgstr ""

#: cinder/network/quantum/melange_connection.py:98
msgid "Connection error contacting melange service, retrying"
msgstr ""

#: cinder/network/quantum/melange_connection.py:108
#, python-format
msgid ""
"allocate IP on network |%(network_id)s| belonging to "
"|%(network_tenant_id)s| to this vif |%(vif_id)s| with mac "
"|%(mac_address)s| belonging to |%(project_id)s| "
msgstr ""

#: cinder/network/quantum/melange_ipam_lib.py:133
msgid "get_project_and_global_net_ids must be called with a non-null project_id"
msgstr ""

#: cinder/network/quantum/cinder_ipam_lib.py:75
msgid "Error creating network entry"
msgstr ""

#: cinder/network/quantum/cinder_ipam_lib.py:90
#, python-format
msgid "No network with net_id = %s"
msgstr ""

#: cinder/network/quantum/cinder_ipam_lib.py:221
#, python-format
msgid "No fixed IPs to deallocate for vif %s"
msgstr ""

#: cinder/network/quantum/quantum_connection.py:99
#, python-format
msgid "Connecting interface %(interface_id)s to net %(net_id)s for %(tenant_id)s"
msgstr ""

#: cinder/network/quantum/quantum_connection.py:113
#, python-format
msgid "Deleting port %(port_id)s on net %(net_id)s for %(tenant_id)s"
msgstr ""

#: cinder/notifier/api.py:115
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: cinder/notifier/api.py:130
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: cinder/notifier/list_notifier.py:65
#, python-format
msgid "Problem '%(e)s' attempting to send to notification driver %(driver)s."
msgstr ""

#: cinder/notifier/rabbit_notifier.py:46
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: cinder/rpc/amqp.py:146
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: cinder/rpc/amqp.py:188
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: cinder/rpc/amqp.py:231
#, python-format
msgid "received %s"
msgstr ""

#: cinder/rpc/amqp.py:236
#, python-format
msgid "no method for message: %s"
msgstr ""

#: cinder/rpc/amqp.py:237
#, python-format
msgid "No method for message: %s"
msgstr ""

#: cinder/rpc/amqp.py:321
#, python-format
msgid "Making asynchronous call on %s ..."
msgstr ""

#: cinder/rpc/amqp.py:324
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: cinder/rpc/amqp.py:346
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: cinder/rpc/amqp.py:354
msgid "Making asynchronous fanout cast..."
msgstr ""

#: cinder/rpc/amqp.py:379
#, python-format
msgid "Sending notification on %s..."
msgstr ""

#: cinder/rpc/common.py:54
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: cinder/rpc/common.py:71
msgid "Timeout while waiting on RPC response."
msgstr ""

#: cinder/rpc/impl_kombu.py:111
msgid "Failed to process message... skipping it."
msgstr ""

#: cinder/rpc/impl_kombu.py:407
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: cinder/rpc/impl_kombu.py:430
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: cinder/rpc/impl_kombu.py:466
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: cinder/rpc/impl_kombu.py:482
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: cinder/rpc/impl_kombu.py:533 cinder/rpc/impl_qpid.py:385
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: cinder/rpc/impl_kombu.py:551 cinder/rpc/impl_qpid.py:400
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: cinder/rpc/impl_kombu.py:555 cinder/rpc/impl_qpid.py:404
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: cinder/rpc/impl_kombu.py:589 cinder/rpc/impl_qpid.py:434
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: cinder/rpc/impl_qpid.py:341
#, python-format
msgid "Unable to connect to AMQP server: %s "
msgstr ""

#: cinder/rpc/impl_qpid.py:346
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: cinder/rpc/impl_qpid.py:354
msgid "Re-established AMQP queues"
msgstr ""

#: cinder/rpc/impl_qpid.py:412
msgid "Error processing message.  Skipping it."
msgstr ""

#: cinder/scheduler/chance.py:47 cinder/scheduler/simple.py:91
#: cinder/scheduler/simple.py:143
msgid "Is the appropriate service running?"
msgstr ""

#: cinder/scheduler/chance.py:52
msgid "Could not find another compute"
msgstr ""

#: cinder/scheduler/driver.py:63
#, python-format
msgid "Casted '%(method)s' to storage '%(host)s'"
msgstr ""

#: cinder/scheduler/driver.py:80
#, python-format
msgid "Casted '%(method)s' to compute '%(host)s'"
msgstr ""

#: cinder/scheduler/driver.py:89
#, python-format
msgid "Casted '%(method)s' to network '%(host)s'"
msgstr ""

#: cinder/scheduler/driver.py:107
#, python-format
msgid "Casted '%(method)s' to %(topic)s '%(host)s'"
msgstr ""

#: cinder/scheduler/driver.py:181
msgid "Must implement a fallback schedule"
msgstr ""

#: cinder/scheduler/driver.py:185
msgid "Driver must implement schedule_prep_resize"
msgstr ""

#: cinder/scheduler/driver.py:190
msgid "Driver must implement schedule_run_instance"
msgstr ""

#: cinder/scheduler/driver.py:325
msgid "Block migration can not be used with shared storage."
msgstr ""

#: cinder/scheduler/driver.py:330
msgid "Live migration can not be used without shared storage."
msgstr ""

#: cinder/scheduler/driver.py:367 cinder/scheduler/driver.py:457
#, python-format
msgid "host %(dest)s is not compatible with original host %(src)s."
msgstr ""

#: cinder/scheduler/driver.py:416
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s to %(dest)s: Lack of "
"memory(host:%(avail)s <= instance:%(mem_inst)s)"
msgstr ""

#: cinder/scheduler/driver.py:472
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s to %(dest)s: Lack of "
"disk(host:%(available)s <= instance:%(necessary)s)"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:51
#, python-format
msgid "No host selection for %s defined."
msgstr ""

#: cinder/scheduler/filter_scheduler.py:64
#, python-format
msgid "Attempting to build %(num_instances)d instance(s)"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:157
msgid "Scheduler only understands Compute nodes (for now)"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:199
#, python-format
msgid "Filtered %(hosts)s"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:209
#, python-format
msgid "Weighted %(weighted_host)s"
msgstr ""

#: cinder/scheduler/host_manager.py:144
#, python-format
msgid "Host filter fails for ignored host %(host)s"
msgstr ""

#: cinder/scheduler/host_manager.py:151
#, python-format
msgid "Host filter fails for non-forced host %(host)s"
msgstr ""

#: cinder/scheduler/host_manager.py:157
#, python-format
msgid "Host filter function %(func)s failed for %(host)s"
msgstr ""

#: cinder/scheduler/host_manager.py:163
#, python-format
msgid "Host filter passes for %(host)s"
msgstr ""

#: cinder/scheduler/host_manager.py:272
#, python-format
msgid "Received %(service_name)s service update from %(host)s."
msgstr ""

#: cinder/scheduler/host_manager.py:313
msgid "host_manager only implemented for 'compute'"
msgstr ""

#: cinder/scheduler/host_manager.py:323
#, python-format
msgid "No service for compute ID %s"
msgstr ""

#: cinder/scheduler/manager.py:85
#, python-format
msgid ""
"Driver Method %(driver_method_name)s missing: %(e)s. Reverting to "
"schedule()"
msgstr ""

#: cinder/scheduler/manager.py:150
#, python-format
msgid "Failed to schedule_%(method)s: %(ex)s"
msgstr ""

#: cinder/scheduler/manager.py:159
#, python-format
msgid "Setting instance %(instance_uuid)s to %(state)s state."
msgstr ""

#: cinder/scheduler/scheduler_options.py:66
#, python-format
msgid "Could not stat scheduler options file %(filename)s: '%(e)s'"
msgstr ""

#: cinder/scheduler/scheduler_options.py:75
#, python-format
msgid "Could not decode scheduler options: '%(e)s'"
msgstr ""

#: cinder/scheduler/simple.py:87
msgid "Not enough allocatable CPU cores remaining"
msgstr ""

#: cinder/scheduler/simple.py:137
msgid "Not enough allocatable storage gigabytes remaining"
msgstr ""

#: cinder/scheduler/filters/core_filter.py:45
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""

#: cinder/tests/fake_utils.py:72
#, python-format
msgid "Faking execution of cmd (subprocess): %s"
msgstr ""

#: cinder/tests/fake_utils.py:80
#, python-format
msgid "Faked command matched %s"
msgstr ""

#: cinder/tests/fake_utils.py:96
#, python-format
msgid "Faked command raised an exception %s"
msgstr ""

#: cinder/tests/fake_utils.py:101
#, python-format
msgid "Reply to faked command is stdout='%(stdout)s' stderr='%(stderr)s'"
msgstr ""

#: cinder/tests/fakelibvirt.py:784
msgid "Please extend mock libvirt module to support flags"
msgstr ""

#: cinder/tests/fakelibvirt.py:790
msgid "Please extend fake libvirt module to support this auth method"
msgstr ""

#: cinder/tests/test_compute.py:365 cinder/tests/test_compute.py:1419
#, python-format
msgid "Running instances: %s"
msgstr ""

#: cinder/tests/test_compute.py:371
#, python-format
msgid "After terminating instances: %s"
msgstr ""

#: cinder/tests/test_compute.py:589
msgid "Internal error"
msgstr ""

#: cinder/tests/test_compute.py:1430
#, python-format
msgid "After force-killing instances: %s"
msgstr ""

#: cinder/tests/test_misc.py:92
#, python-format
msgid ""
"The following migrations are missing a downgrade:\n"
"\t%s"
msgstr ""

#: cinder/tests/test_cinder_manage.py:169
msgid "id"
msgstr ""

#: cinder/tests/test_cinder_manage.py:170
msgid "IPv4"
msgstr ""

#: cinder/tests/test_cinder_manage.py:171
msgid "IPv6"
msgstr ""

#: cinder/tests/test_cinder_manage.py:172
msgid "start address"
msgstr ""

#: cinder/tests/test_cinder_manage.py:173
msgid "DNS1"
msgstr ""

#: cinder/tests/test_cinder_manage.py:174
msgid "DNS2"
msgstr ""

#: cinder/tests/test_cinder_manage.py:175
msgid "VlanID"
msgstr ""

#: cinder/tests/test_cinder_manage.py:176
msgid "project"
msgstr ""

#: cinder/tests/test_cinder_manage.py:177
msgid "uuid"
msgstr ""

#: cinder/tests/test_storage.py:216
#, python-format
msgid "Target %s allocated"
msgstr ""

#: cinder/tests/test_storage.py:468
#, python-format
msgid "Cannot confirm exported storage id:%s."
msgstr ""

#: cinder/tests/test_storage_types.py:58
#, python-format
msgid "Given data: %s"
msgstr ""

#: cinder/tests/test_storage_types.py:59
#, python-format
msgid "Result data: %s"
msgstr ""

#: cinder/tests/test_xenapi.py:626
#, python-format
msgid "Creating files in %s to simulate guest agent"
msgstr ""

#: cinder/tests/test_xenapi.py:637
#, python-format
msgid "Removing simulated guest agent files in %s"
msgstr ""

#: cinder/tests/api/openstack/compute/test_servers.py:2144
#, python-format
msgid "Quota exceeded: code=%(code)s"
msgstr ""

#: cinder/tests/api/openstack/compute/contrib/test_snapshots.py:57
#, python-format
msgid "_create: %s"
msgstr ""

#: cinder/tests/api/openstack/compute/contrib/test_snapshots.py:66
#, python-format
msgid "_delete: %s"
msgstr ""

#: cinder/tests/api/openstack/compute/contrib/test_snapshots.py:75
#, python-format
msgid "_get: %s"
msgstr ""

#: cinder/tests/api/openstack/compute/contrib/test_snapshots.py:85
#, python-format
msgid "_get_all: %s"
msgstr ""

#: cinder/tests/api/openstack/compute/contrib/test_snapshots.py:125
#, python-format
msgid "test_snapshot_create: param=%s"
msgstr ""

#: cinder/tests/api/openstack/compute/contrib/test_snapshots.py:134
#, python-format
msgid "test_snapshot_create: resp_dict=%s"
msgstr ""

#: cinder/tests/api/openstack/compute/contrib/test_snapshots.py:156
#, python-format
msgid "test_snapshot_create_force: param=%s"
msgstr ""

#: cinder/tests/api/openstack/compute/contrib/test_snapshots.py:165
#, python-format
msgid "test_snapshot_create_force: resp_dict=%s"
msgstr ""

#: cinder/tests/api/openstack/compute/contrib/test_snapshots.py:205
#, python-format
msgid "test_snapshot_show: resp=%s"
msgstr ""

#: cinder/tests/api/openstack/compute/contrib/test_snapshots.py:231
#, python-format
msgid "test_snapshot_detail: resp_dict=%s"
msgstr ""

#: cinder/tests/integrated/test_login.py:31
#, python-format
msgid "flavor: %s"
msgstr ""

#: cinder/tests/integrated/api/client.py:38
#, python-format
msgid ""
"%(message)s\n"
"Status Code: %(_status)s\n"
"Body: %(_body)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:47
msgid "Authentication error"
msgstr ""

#: cinder/tests/integrated/api/client.py:55
msgid "Authorization error"
msgstr ""

#: cinder/tests/integrated/api/client.py:63
msgid "Item not found"
msgstr ""

#: cinder/tests/integrated/api/client.py:105
#, python-format
msgid "Doing %(method)s on %(relative_url)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:107
#, python-format
msgid "Body: %s"
msgstr ""

#: cinder/tests/integrated/api/client.py:125
#, python-format
msgid "%(auth_uri)s => code %(http_status)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:151
#, python-format
msgid "%(relative_uri)s => code %(http_status)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:161
msgid "Unexpected status code"
msgstr ""

#: cinder/tests/integrated/api/client.py:168
#, python-format
msgid "Decoding JSON: %s"
msgstr ""

#: cinder/tests/rpc/common.py:133
#, python-format
msgid "Nested received %(queue)s, %(value)s"
msgstr ""

#: cinder/tests/rpc/common.py:142
#, python-format
msgid "Nested return %s"
msgstr ""

#: cinder/tests/rpc/common.py:160
msgid "RPC backend does not support timeouts"
msgstr ""

#: cinder/tests/rpc/common.py:227 cinder/tests/rpc/common.py:233
#, python-format
msgid "Received %s"
msgstr ""

#: cinder/virt/connection.py:85
msgid "Failed to open connection to the hypervisor"
msgstr ""

#: cinder/virt/fake.py:270 cinder/virt/xenapi_conn.py:396
#: cinder/virt/baremetal/proxy.py:716 cinder/virt/libvirt/connection.py:2045
#, python-format
msgid "Compute_service record created for %s "
msgstr ""

#: cinder/virt/fake.py:273 cinder/virt/xenapi_conn.py:399
#: cinder/virt/baremetal/proxy.py:720 cinder/virt/libvirt/connection.py:2048
#, python-format
msgid "Compute_service record updated for %s "
msgstr ""

#: cinder/virt/firewall.py:130
#, python-format
msgid "Attempted to unfilter instance %s which is not filtered"
msgstr ""

#: cinder/virt/firewall.py:137
#, python-format
msgid "Filters added to instance %s"
msgstr ""

#: cinder/virt/firewall.py:139
msgid "Provider Firewall Rules refreshed"
msgstr ""

#: cinder/virt/firewall.py:291
#, python-format
msgid "Adding security group rule: %r"
msgstr ""

#: cinder/virt/firewall.py:403 cinder/virt/xenapi/firewall.py:87
#, python-format
msgid "Adding provider rule: %s"
msgstr ""

#: cinder/virt/images.py:86
msgid "'qemu-img info' parsing failed."
msgstr ""

#: cinder/virt/images.py:92
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: cinder/virt/images.py:104
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: cinder/virt/vmwareapi_conn.py:105
msgid ""
"Must specify vmwareapi_host_ip,vmwareapi_host_username and "
"vmwareapi_host_password to useconnection_type=vmwareapi"
msgstr ""

#: cinder/virt/vmwareapi_conn.py:276
#, python-format
msgid "In vmwareapi:_create_session, got this exception: %s"
msgstr ""

#: cinder/virt/vmwareapi_conn.py:359
#, python-format
msgid "In vmwareapi:_call_method, got this exception: %s"
msgstr ""

#: cinder/virt/vmwareapi_conn.py:398
#, python-format
msgid "Task [%(task_name)s] %(task_ref)s status: success"
msgstr ""

#: cinder/virt/vmwareapi_conn.py:404
#, python-format
msgid "Task [%(task_name)s] %(task_ref)s status: error %(error_info)s"
msgstr ""

#: cinder/virt/vmwareapi_conn.py:409
#, python-format
msgid "In vmwareapi:_poll_task, Got this error %s"
msgstr ""

#: cinder/virt/xenapi_conn.py:140
msgid ""
"Must specify xenapi_connection_url, xenapi_connection_username "
"(optionally), and xenapi_connection_password to use "
"connection_type=xenapi"
msgstr ""

#: cinder/virt/xenapi_conn.py:329 cinder/virt/libvirt/connection.py:472
msgid "Could not determine iscsi initiator name"
msgstr ""

#: cinder/virt/xenapi_conn.py:460
msgid "Host startup on XenServer is not supported."
msgstr ""

#: cinder/virt/xenapi_conn.py:489
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr ""

#: cinder/virt/xenapi_conn.py:527
msgid "Host is member of a pool, but DB says otherwise"
msgstr ""

#: cinder/virt/xenapi_conn.py:599 cinder/virt/xenapi_conn.py:612
#, python-format
msgid "Got exception: %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:93
msgid "No domains exist."
msgstr ""

#: cinder/virt/baremetal/dom.py:95
#, python-format
msgid "============= initial domains =========== : %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:99
msgid "Building domain: to be removed"
msgstr ""

#: cinder/virt/baremetal/dom.py:103
msgid "Not running domain: remove"
msgstr ""

#: cinder/virt/baremetal/dom.py:111
msgid "domain running on an unknown node: discarded"
msgstr ""

#: cinder/virt/baremetal/dom.py:127
#, python-format
msgid "No such domain (%s)"
msgstr ""

#: cinder/virt/baremetal/dom.py:134
#, python-format
msgid "Failed power down Bare-metal node %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:143
msgid "deactivate -> activate fails"
msgstr ""

#: cinder/virt/baremetal/dom.py:153
msgid "destroy_domain: no such domain"
msgstr ""

#: cinder/virt/baremetal/dom.py:154
#, python-format
msgid "No such domain %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:161
#, python-format
msgid "Domains: %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:163
#, python-format
msgid "Nodes: %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:166
#, python-format
msgid "After storing domains: %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:169
msgid "deactivation/removing domain failed"
msgstr ""

#: cinder/virt/baremetal/dom.py:176
msgid "===== Domain is being created ====="
msgstr ""

#: cinder/virt/baremetal/dom.py:179
msgid "Same domain name already exists"
msgstr ""

#: cinder/virt/baremetal/dom.py:181
msgid "create_domain: before get_idle_node"
msgstr ""

#: cinder/virt/baremetal/dom.py:198
#, python-format
msgid "Created new domain: %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:213
#, python-format
msgid "Failed to boot Bare-metal node %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:222
msgid "No such domain exists"
msgstr ""

#: cinder/virt/baremetal/dom.py:226
#, python-format
msgid "change_domain_state: to new state %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:233
#, python-format
msgid "Stored fake domains to the file: %s"
msgstr ""

#: cinder/virt/baremetal/dom.py:244
msgid "domain does not exist"
msgstr ""

#: cinder/virt/baremetal/nodes.py:42
#, python-format
msgid "Unknown baremetal driver %(d)s"
msgstr ""

#: cinder/virt/baremetal/proxy.py:148
#, python-format
msgid "Error encountered when destroying instance '%(name)s': %(ex)s"
msgstr ""

#: cinder/virt/baremetal/proxy.py:162
#, python-format
msgid "instance %(instance_name)s: deleting instance files %(target)s"
msgstr ""

#: cinder/virt/baremetal/proxy.py:189
#, python-format
msgid "instance %s: rebooted"
msgstr ""

#: cinder/virt/baremetal/proxy.py:192
msgid "_wait_for_reboot failed"
msgstr ""

#: cinder/virt/baremetal/proxy.py:222
#, python-format
msgid "instance %s: rescued"
msgstr ""

#: cinder/virt/baremetal/proxy.py:225
msgid "_wait_for_rescue failed"
msgstr ""

#: cinder/virt/baremetal/proxy.py:242
msgid "<============= spawn of baremetal =============>"
msgstr ""

#: cinder/virt/baremetal/proxy.py:255
#, python-format
msgid "instance %s: is building"
msgstr ""

#: cinder/virt/baremetal/proxy.py:260
msgid "Key is injected but instance is not running yet"
msgstr ""

#: cinder/virt/baremetal/proxy.py:265
#, python-format
msgid "instance %s: booted"
msgstr ""

#: cinder/virt/baremetal/proxy.py:268
#, python-format
msgid "~~~~~~ current state = %s ~~~~~~"
msgstr ""

#: cinder/virt/baremetal/proxy.py:269
#, python-format
msgid "instance %s spawned successfully"
msgstr ""

#: cinder/virt/baremetal/proxy.py:272
#, python-format
msgid "instance %s:not booted"
msgstr ""

#: cinder/virt/baremetal/proxy.py:274
msgid "Bremetal assignment is overcommitted."
msgstr ""

#: cinder/virt/baremetal/proxy.py:354
#, python-format
msgid "instance %s: Creating image"
msgstr ""

#: cinder/virt/baremetal/proxy.py:473
#, python-format
msgid "instance %(inst_name)s: injecting %(injection)s into image %(img_id)s"
msgstr ""

#: cinder/virt/baremetal/proxy.py:484
#, python-format
msgid ""
"instance %(inst_name)s: ignoring error injecting data into image "
"%(img_id)s (%(e)s)"
msgstr ""

#: cinder/virt/baremetal/proxy.py:529
#, python-format
msgid "instance %s: starting toXML method"
msgstr ""

#: cinder/virt/baremetal/proxy.py:531
#, python-format
msgid "instance %s: finished toXML method"
msgstr ""

#: cinder/virt/baremetal/proxy.py:574 cinder/virt/libvirt/connection.py:1815
msgid ""
"Cannot get the number of cpu, because this function is not implemented "
"for this platform. This error can be safely ignored for now."
msgstr ""

#: cinder/virt/baremetal/proxy.py:714
#, python-format
msgid "#### RLK: cpu_arch = %s "
msgstr ""

#: cinder/virt/baremetal/proxy.py:746
msgid "Updating!"
msgstr ""

#: cinder/virt/baremetal/proxy.py:773 cinder/virt/libvirt/connection.py:2609
#: cinder/virt/xenapi/host.py:129
msgid "Updating host stats"
msgstr ""

#: cinder/virt/baremetal/tilera.py:185
msgid "free_node...."
msgstr ""

#: cinder/virt/baremetal/tilera.py:216
#, python-format
msgid "deactivate_node is called for node_id = %(id)s node_ip = %(ip)s"
msgstr ""

#: cinder/virt/baremetal/tilera.py:221
msgid "status of node is set to 0"
msgstr ""

#: cinder/virt/baremetal/tilera.py:232
msgid "rootfs is already removed"
msgstr ""

#: cinder/virt/baremetal/tilera.py:264
msgid "Before ping to the bare-metal node"
msgstr ""

#: cinder/virt/baremetal/tilera.py:275
#, python-format
msgid "TILERA_BOARD_#%(node_id)s %(node_ip)s is ready"
msgstr ""

#: cinder/virt/baremetal/tilera.py:279
#, python-format
msgid "TILERA_BOARD_#%(node_id)s %(node_ip)s is not ready, out_msg=%(out_msg)s"
msgstr ""

#: cinder/virt/baremetal/tilera.py:292
msgid "Noting to do for tilera nodes: vmlinux is in CF"
msgstr ""

#: cinder/virt/baremetal/tilera.py:316
msgid "activate_node"
msgstr ""

#: cinder/virt/baremetal/tilera.py:330
msgid "Node is unknown error state."
msgstr ""

#: cinder/virt/disk/api.py:165
msgid "no capable image handler configured"
msgstr ""

#: cinder/virt/disk/api.py:178
#, python-format
msgid "unknown disk image handler: %s"
msgstr ""

#: cinder/virt/disk/api.py:189
msgid "image already mounted"
msgstr ""

#: cinder/virt/disk/api.py:276 cinder/virt/disk/guestfs.py:64
#: cinder/virt/disk/guestfs.py:78 cinder/virt/disk/mount.py:100
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr ""

#: cinder/virt/disk/api.py:291
#, python-format
msgid "Failed to remove container: %s"
msgstr ""

#: cinder/virt/disk/api.py:441
#, python-format
msgid "User %(username)s not found in password file."
msgstr ""

#: cinder/virt/disk/api.py:457
#, python-format
msgid "User %(username)s not found in shadow file."
msgstr ""

#: cinder/virt/disk/guestfs.py:39
#, python-format
msgid "unsupported partition: %s"
msgstr ""

#: cinder/virt/disk/guestfs.py:77
msgid "unknown guestmount error"
msgstr ""

#: cinder/virt/disk/loop.py:30
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr ""

#: cinder/virt/disk/mount.py:76
msgid "no partitions found"
msgstr ""

#: cinder/virt/disk/mount.py:77
#, python-format
msgid "Failed to map partitions: %s"
msgstr ""

#: cinder/virt/disk/nbd.py:58
msgid "nbd unavailable: module not loaded"
msgstr ""

#: cinder/virt/disk/nbd.py:63
msgid "No free nbd devices"
msgstr ""

#: cinder/virt/disk/nbd.py:81
#, python-format
msgid "qemu-nbd error: %s"
msgstr ""

#: cinder/virt/disk/nbd.py:93
#, python-format
msgid "nbd device %s did not show up"
msgstr ""

#: cinder/virt/libvirt/connection.py:265
#, python-format
msgid "Connecting to libvirt: %s"
msgstr ""

#: cinder/virt/libvirt/connection.py:286
msgid "Connection to libvirt broke"
msgstr ""

#: cinder/virt/libvirt/connection.py:388
#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: cinder/virt/libvirt/connection.py:400
#, python-format
msgid ""
"Error from libvirt during saved instance removal. Code=%(errcode)s "
"Error=%(e)s"
msgstr ""

#: cinder/virt/libvirt/connection.py:411
#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: cinder/virt/libvirt/connection.py:423
msgid "Instance destroyed successfully."
msgstr ""

#: cinder/virt/libvirt/connection.py:435
#, python-format
msgid "Error from libvirt during unfilter. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: cinder/virt/libvirt/connection.py:461
#, python-format
msgid "Deleting instance files %(target)s"
msgstr ""

#: cinder/virt/libvirt/connection.py:554
msgid "attaching LXC block device"
msgstr ""

#: cinder/virt/libvirt/connection.py:567
msgid "detaching LXC block device"
msgstr ""

#: cinder/virt/libvirt/connection.py:692
msgid "Instance soft rebooted successfully."
msgstr ""

#: cinder/virt/libvirt/connection.py:696
msgid "Failed to soft reboot instance."
msgstr ""

#: cinder/virt/libvirt/connection.py:725
msgid "Instance shutdown successfully."
msgstr ""

#: cinder/virt/libvirt/connection.py:761 cinder/virt/libvirt/connection.py:905
msgid "During reboot, instance disappeared."
msgstr ""

#: cinder/virt/libvirt/connection.py:766
msgid "Instance rebooted successfully."
msgstr ""

#: cinder/virt/libvirt/connection.py:867 cinder/virt/xenapi/vmops.py:1358
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""

#: cinder/virt/libvirt/connection.py:871
#, python-format
msgid "Automatically confirming migration %d"
msgstr ""

#: cinder/virt/libvirt/connection.py:896
msgid "Instance is running"
msgstr ""

#: cinder/virt/libvirt/connection.py:910
msgid "Instance spawned successfully."
msgstr ""

#: cinder/virt/libvirt/connection.py:926
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr ""

#: cinder/virt/libvirt/connection.py:978
msgid "Guest does not have a console available"
msgstr ""

#: cinder/virt/libvirt/connection.py:1020
#, python-format
msgid "Path '%(path)s' supports direct I/O"
msgstr ""

#: cinder/virt/libvirt/connection.py:1024
#, python-format
msgid "Path '%(path)s' does not support direct I/O: '%(ex)s'"
msgstr ""

#: cinder/virt/libvirt/connection.py:1028 cinder/virt/libvirt/connection.py:1032
#, python-format
msgid "Error on '%(path)s' while checking direct I/O: '%(ex)s'"
msgstr ""

#: cinder/virt/libvirt/connection.py:1153
msgid "Creating image"
msgstr ""

#: cinder/virt/libvirt/connection.py:1339
#, python-format
msgid "Injecting %(injection)s into image %(img_id)s"
msgstr ""

#: cinder/virt/libvirt/connection.py:1349
#, python-format
msgid "Ignoring error injecting data into image %(img_id)s (%(e)s)"
msgstr ""

#: cinder/virt/libvirt/connection.py:1381
#, python-format
msgid "block_device_list %s"
msgstr ""

#: cinder/virt/libvirt/connection.py:1658
msgid "Starting toXML method"
msgstr ""

#: cinder/virt/libvirt/connection.py:1662
msgid "Finished toXML method"
msgstr ""

#: cinder/virt/libvirt/connection.py:1679
#, python-format
msgid ""
"Error from libvirt while looking up %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: cinder/virt/libvirt/connection.py:1920
msgid "libvirt version is too old (does not support getVersion)"
msgstr ""

#: cinder/virt/libvirt/connection.py:1942
#, python-format
msgid "'<cpu>' must be 1, but %d\n"
msgstr ""

#: cinder/virt/libvirt/connection.py:1969
#, python-format
msgid "topology (%(topology)s) must have %(ks)s"
msgstr ""

#: cinder/virt/libvirt/connection.py:2067
#, python-format
msgid ""
"Instance launched has CPU info:\n"
"%s"
msgstr ""

#: cinder/virt/libvirt/connection.py:2079
#, python-format
msgid ""
"CPU doesn't have compatibility.\n"
"\n"
"%(ret)s\n"
"\n"
"Refer to %(u)s"
msgstr ""

#: cinder/virt/libvirt/connection.py:2136
#, python-format
msgid "Timeout migrating for %s. nwfilter not found."
msgstr ""

#: cinder/virt/libvirt/connection.py:2352
#, python-format
msgid "skipping %(path)s since it looks like storage"
msgstr ""

#: cinder/virt/libvirt/connection.py:2407
#, python-format
msgid "Getting disk size of %(i_name)s: %(e)s"
msgstr ""

#: cinder/virt/libvirt/connection.py:2458
#, python-format
msgid "Instance %s: Starting migrate_disk_and_power_off"
msgstr ""

#: cinder/virt/libvirt/connection.py:2513
msgid "During wait running, instance disappeared."
msgstr ""

#: cinder/virt/libvirt/connection.py:2518
msgid "Instance running successfully."
msgstr ""

#: cinder/virt/libvirt/connection.py:2525
#, python-format
msgid "Instance %s: Starting finish_migration"
msgstr ""

#: cinder/virt/libvirt/connection.py:2565
#, python-format
msgid "Instance %s: Starting finish_revert_migration"
msgstr ""

#: cinder/virt/libvirt/firewall.py:42
msgid ""
"Libvirt module could not be loaded. NWFilterFirewall will not work "
"correctly."
msgstr ""

#: cinder/virt/libvirt/firewall.py:93
msgid "Called setup_basic_filtering in nwfilter"
msgstr ""

#: cinder/virt/libvirt/firewall.py:101
msgid "Ensuring static filters"
msgstr ""

#: cinder/virt/libvirt/firewall.py:171
#, python-format
msgid "The nwfilter(%(instance_filter_name)s) is not found."
msgstr ""

#: cinder/virt/libvirt/firewall.py:217
#, python-format
msgid "The nwfilter(%(instance_filter_name)s) for%(name)s is not found."
msgstr ""

#: cinder/virt/libvirt/firewall.py:233
msgid "iptables firewall: Setup Basic Filtering"
msgstr ""

#: cinder/virt/libvirt/firewall.py:252
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:170
#, python-format
msgid "%s is a valid instance name"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:173
#, python-format
msgid "%s has a disk file"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:175
#, python-format
msgid "Instance %(instance)s is backed by %(backing)s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:186
#, python-format
msgid ""
"Instance %(instance)s is using a backing file %(backing)s which does not "
"appear in the image service"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:237
#, python-format
msgid "%(id)s (%(base_file)s): image verification failed"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:247
#, python-format
msgid "%(id)s (%(base_file)s): image verification skipped, no hash stored"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:266
#, python-format
msgid "Cannot remove %(base_file)s, it does not exist"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:278
#, python-format
msgid "Base file too young to remove: %s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:281
#, python-format
msgid "Removing base file: %s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:288
#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:299
#, python-format
msgid "%(id)s (%(base_file)s): checking"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:318
#, python-format
msgid ""
"%(id)s (%(base_file)s): in use: on this node %(local)d local, %(remote)d "
"on other nodes"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:330
#, python-format
msgid ""
"%(id)s (%(base_file)s): warning -- an absent base file is in use! "
"instances: %(instance_list)s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:338
#, python-format
msgid "%(id)s (%(base_file)s): in use on (%(remote)d on other nodes)"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:348
#, python-format
msgid "%(id)s (%(base_file)s): image is not in use"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:354
#, python-format
msgid "%(id)s (%(base_file)s): image is in use"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:377
#, python-format
msgid "Skipping verification, no base directory at %s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:381
msgid "Verify base images"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:388
#, python-format
msgid "Image id %(id)s yields fingerprint %(fingerprint)s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:406
#, python-format
msgid "Unknown base file: %s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:411
#, python-format
msgid "Active base files: %s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:414
#, python-format
msgid "Corrupt base files: %s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:418
#, python-format
msgid "Removable base files: %s"
msgstr ""

#: cinder/virt/libvirt/imagecache.py:426
msgid "Verification complete"
msgstr ""

#: cinder/virt/libvirt/utils.py:264
msgid "Unable to find an open port"
msgstr ""

#: cinder/virt/libvirt/vif.py:90
#, python-format
msgid "Ensuring vlan %(vlan)s and bridge %(bridge)s"
msgstr ""

#: cinder/virt/libvirt/vif.py:99
#, python-format
msgid "Ensuring bridge %s"
msgstr ""

#: cinder/virt/libvirt/vif.py:165 cinder/virt/libvirt/vif.py:220
#, python-format
msgid "Failed while unplugging vif of instance '%s'"
msgstr ""

#: cinder/virt/libvirt/storage.py:163
#, python-format
msgid "iSCSI device not found at %s"
msgstr ""

#: cinder/virt/libvirt/storage.py:166
#, python-format
msgid ""
"ISCSI storage not yet found at: %(mount_device)s. Will rescan & retry.  "
"Try number: %(tries)s"
msgstr ""

#: cinder/virt/libvirt/storage.py:178
#, python-format
msgid "Found iSCSI node %(mount_device)s (after %(tries)s rescans)"
msgstr ""

#: cinder/virt/vmwareapi/error_util.py:93
#, python-format
msgid "Error(s) %s occurred in the call to RetrieveProperties"
msgstr ""

#: cinder/virt/vmwareapi/fake.py:44 cinder/virt/xenapi/fake.py:77
#, python-format
msgid "%(text)s: _db_content => %(content)s"
msgstr ""

#: cinder/virt/vmwareapi/fake.py:131
#, python-format
msgid "Property %(attr)s not set for the managed object %(objName)s"
msgstr ""

#: cinder/virt/vmwareapi/fake.py:437
msgid "There is no VM registered"
msgstr ""

#: cinder/virt/vmwareapi/fake.py:439 cinder/virt/vmwareapi/fake.py:609
#, python-format
msgid "Virtual Machine with ref %s is not there"
msgstr ""

#: cinder/virt/vmwareapi/fake.py:502
#, python-format
msgid "Logging out a session that is invalid or already logged out: %s"
msgstr ""

#: cinder/virt/vmwareapi/fake.py:517
msgid "Session is faulty"
msgstr ""

#: cinder/virt/vmwareapi/fake.py:520
msgid "Session Invalid"
msgstr ""

#: cinder/virt/vmwareapi/fake.py:606
msgid " No Virtual Machine has been registered yet"
msgstr ""

#: cinder/virt/vmwareapi/io_util.py:99
#, python-format
msgid "Glance image %s is in killed state"
msgstr ""

#: cinder/virt/vmwareapi/io_util.py:107
#, python-format
msgid "Glance image %(image_id)s is in unknown state - %(state)s"
msgstr ""

#: cinder/virt/vmwareapi/network_utils.py:128
msgid ""
"ESX SOAP server returned an empty port group for the host system in its "
"response"
msgstr ""

#: cinder/virt/vmwareapi/network_utils.py:155
#, python-format
msgid "Creating Port Group with name %s on the ESX host"
msgstr ""

#: cinder/virt/vmwareapi/network_utils.py:169
#, python-format
msgid "Created Port Group with name %s on the ESX host"
msgstr ""

#: cinder/virt/vmwareapi/read_write_util.py:150
#, python-format
msgid "Exception during HTTP connection close in VMWareHTTpWrite. Exception is %s"
msgstr ""

#: cinder/virt/vmwareapi/vim.py:84
msgid "Unable to import suds."
msgstr ""

#: cinder/virt/vmwareapi/vim.py:90
msgid "Must specify vmwareapi_wsdl_loc"
msgstr ""

#: cinder/virt/vmwareapi/vim.py:145
#, python-format
msgid "No such SOAP method '%s' provided by VI SDK"
msgstr ""

#: cinder/virt/vmwareapi/vim.py:150
#, python-format
msgid "httplib error in %s: "
msgstr ""

#: cinder/virt/vmwareapi/vim.py:157
#, python-format
msgid "Socket error in %s: "
msgstr ""

#: cinder/virt/vmwareapi/vim.py:162
#, python-format
msgid "Type error in  %s: "
msgstr ""

#: cinder/virt/vmwareapi/vim.py:166
#, python-format
msgid "Exception in %s "
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:66
msgid "Getting list of instances"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:82
#, python-format
msgid "Got total of %s instances"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:126
msgid "Couldn't get a local Datastore reference"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:196
#, python-format
msgid "Creating VM with the name %s on the ESX  host"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:205
#, python-format
msgid "Created VM with the name %s on the ESX  host"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:234
#, python-format
msgid ""
"Creating Virtual Disk of size  %(vmdk_file_size_in_kb)s KB and adapter "
"type  %(adapter_type)s on the ESX host local store %(data_store_name)s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:251
#, python-format
msgid ""
"Created Virtual Disk of size %(vmdk_file_size_in_kb)s KB on the ESX host "
"local store %(data_store_name)s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:260
#, python-format
msgid ""
"Deleting the file %(flat_uploaded_vmdk_path)s on the ESX host localstore "
"%(data_store_name)s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:272
#, python-format
msgid ""
"Deleted the file %(flat_uploaded_vmdk_path)s on the ESX host local store "
"%(data_store_name)s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:283
#, python-format
msgid ""
"Downloading image file data %(image_ref)s to the ESX data store "
"%(data_store_name)s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:298
#, python-format
msgid ""
"Downloaded image file data %(image_ref)s to the ESX data store "
"%(data_store_name)s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:315
#, python-format
msgid "Reconfiguring VM instance %s to attach the image disk"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:322
#, python-format
msgid "Reconfigured VM instance %s to attach the image disk"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:329
#, python-format
msgid "Powering on the VM instance %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:335
#, python-format
msgid "Powered on the VM instance %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:381
#, python-format
msgid "Creating Snapshot of the VM instance %s "
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:391
#, python-format
msgid "Created Snapshot of the VM instance %s "
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:434
#, python-format
msgid "Copying disk data before snapshot of the VM  instance %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:447
#, python-format
msgid "Copied disk data before snapshot of the VM instance %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:456
#, python-format
msgid "Uploading image %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:469
#, python-format
msgid "Uploaded image %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:479
#, python-format
msgid "Deleting temporary vmdk file %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:488
#, python-format
msgid "Deleted temporary vmdk file %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:520
msgid "instance is not powered on"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:527
#, python-format
msgid "Rebooting guest OS of VM %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:530
#, python-format
msgid "Rebooted guest OS of VM %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:532
#, python-format
msgid "Doing hard reboot of VM %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:536
#, python-format
msgid "Did hard reboot of VM %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:548
#, python-format
msgid "instance - %s not present"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:567
#, python-format
msgid "Powering off the VM %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:572
#, python-format
msgid "Powered off the VM %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:576
#, python-format
msgid "Unregistering the VM %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:579
#, python-format
msgid "Unregistered the VM %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:581
#, python-format
msgid ""
"In vmwareapi:vmops:destroy, got this exception while un-registering the "
"VM: %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:592
#, python-format
msgid "Deleting contents of the VM %(name)s from datastore %(datastore_name)s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:602
#, python-format
msgid "Deleted contents of the VM %(name)s from datastore %(datastore_name)s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:607
#, python-format
msgid ""
"In vmwareapi:vmops:destroy, got this exception while deleting the VM "
"contents from the disk: %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:615
msgid "pause not supported for vmwareapi"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:619
msgid "unpause not supported for vmwareapi"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:633
#, python-format
msgid "Suspending the VM %s "
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:637
#, python-format
msgid "Suspended the VM %s "
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:640
msgid "instance is powered off and can not be suspended."
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:643
#, python-format
msgid "VM %s was already in suspended state. So returning without doing anything"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:656
#, python-format
msgid "Resuming the VM %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:661
#, python-format
msgid "Resumed the VM %s "
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:663
msgid "instance is not in a suspended state"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:699
msgid "get_diagnostics not implemented for vmwareapi"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:757
#, python-format
msgid ""
"Reconfiguring VM instance %(name)s to set the machine id with ip - "
"%(ip_addr)s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:765
#, python-format
msgid ""
"Reconfigured VM instance %(name)s to set the machine id with ip - "
"%(ip_addr)s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:802
#, python-format
msgid "Creating directory with path %s"
msgstr ""

#: cinder/virt/vmwareapi/vmops.py:806
#, python-format
msgid "Created directory with path %s"
msgstr ""

#: cinder/virt/vmwareapi/vmware_images.py:89
#, python-format
msgid "Downloading image %s from glance image server"
msgstr ""

#: cinder/virt/vmwareapi/vmware_images.py:103
#, python-format
msgid "Downloaded image %s from glance image server"
msgstr ""

#: cinder/virt/vmwareapi/vmware_images.py:108
#, python-format
msgid "Uploading image %s to the Glance image server"
msgstr ""

#: cinder/virt/vmwareapi/vmware_images.py:129
#, python-format
msgid "Uploaded image %s to the Glance image server"
msgstr ""

#: cinder/virt/vmwareapi/vmware_images.py:139
#, python-format
msgid "Getting image size for the image %s"
msgstr ""

#: cinder/virt/vmwareapi/vmware_images.py:143
#, python-format
msgid "Got image size of %(size)s for the image %(image)s"
msgstr ""

#: cinder/virt/xenapi/fake.py:553 cinder/virt/xenapi/fake.py:652
#: cinder/virt/xenapi/fake.py:670 cinder/virt/xenapi/fake.py:732
msgid "Raising NotImplemented"
msgstr ""

#: cinder/virt/xenapi/fake.py:555
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr ""

#: cinder/virt/xenapi/fake.py:589
#, python-format
msgid "Calling %(localname)s %(impl)s"
msgstr ""

#: cinder/virt/xenapi/fake.py:594
#, python-format
msgid "Calling getter %s"
msgstr ""

#: cinder/virt/xenapi/fake.py:654
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""

#: cinder/virt/xenapi/host.py:67
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database:"
" assuming it is a worker VM and skipping migration to a new host"
msgstr ""

#: cinder/virt/xenapi/host.py:137
#, python-format
msgid "Unable to get SR for this host: %s"
msgstr ""

#: cinder/virt/xenapi/host.py:169
msgid "Unable to get updated status"
msgstr ""

#: cinder/virt/xenapi/host.py:172
#, python-format
msgid "The call to %(method)s returned an error: %(e)s."
msgstr ""

#: cinder/virt/xenapi/network_utils.py:37
#, python-format
msgid "Found non-unique network for name_label %s"
msgstr ""

#: cinder/virt/xenapi/network_utils.py:55
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr ""

#: cinder/virt/xenapi/network_utils.py:58
#, python-format
msgid "Found no network for bridge %s"
msgstr ""

#: cinder/virt/xenapi/pool.py:111
#, python-format
msgid "Unable to eject %(host)s from the pool; pool not empty"
msgstr ""

#: cinder/virt/xenapi/pool.py:126
#, python-format
msgid "Unable to eject %(host)s from the pool; No master found"
msgstr ""

#: cinder/virt/xenapi/pool.py:143
#, python-format
msgid "Pool-Join failed: %(e)s"
msgstr ""

#: cinder/virt/xenapi/pool.py:146
#, python-format
msgid "Unable to join %(host)s in the pool"
msgstr ""

#: cinder/virt/xenapi/pool.py:162
#, python-format
msgid "Pool-eject failed: %(e)s"
msgstr ""

#: cinder/virt/xenapi/pool.py:174
#, python-format
msgid "Unable to set up pool: %(e)s."
msgstr ""

#: cinder/virt/xenapi/pool.py:185
#, python-format
msgid "Pool-set_name_label failed: %(e)s"
msgstr ""

#: cinder/virt/xenapi/vif.py:103
#, python-format
msgid "Found no PIF for device %s"
msgstr ""

#: cinder/virt/xenapi/vif.py:122
#, python-format
msgid ""
"PIF %(pif_rec['uuid'])s for network %(bridge)s has VLAN id %(pif_vlan)d. "
"Expected %(vlan_num)d"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:218
msgid "Created VM"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:245
#, python-format
msgid "VBD not found in instance %s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:262
#, python-format
msgid "VBD %s already detached"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:265
#, python-format
msgid "VBD %(vbd_ref)s detach rejected, attempt %(num_attempt)d/%(max_attempts)d"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:270
#, python-format
msgid "Unable to unplug VBD %s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:275
#, python-format
msgid "Reached maximum number of retries trying to unplug VBD %s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:286
#, python-format
msgid "Unable to destroy VBD %s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:305
#, python-format
msgid "Creating %(vbd_type)s-type VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:308
#, python-format
msgid "Created VBD %(vbd_ref)s for VM %(vm_ref)s, VDI %(vdi_ref)s."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:319
#, python-format
msgid "Unable to destroy VDI %s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:336
#, python-format
msgid ""
"Created VDI %(vdi_ref)s (%(name_label)s, %(virtual_size)s, %(read_only)s)"
" on %(sr_ref)s."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:345
#, python-format
msgid "Copied VDI %(vdi_ref)s from VDI %(vdi_to_copy_ref)s on %(sr_ref)s."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:353
#, python-format
msgid "Cloned VDI %(vdi_ref)s from VDI %(vdi_to_clone_ref)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:372
#, python-format
msgid "No primary VDI found for %(vm_ref)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:379
#, python-format
msgid "Snapshotting with label '%(label)s'"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:392
#, python-format
msgid "Created snapshot %(template_vm_ref)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:431
#, python-format
msgid "Asking xapi to upload %(vdi_uuids)s as ID %(image_id)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:583
#, python-format
msgid "Creating blank HD of size %(req_size)d gigs"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:634
#, python-format
msgid ""
"Fast cloning is only supported on default local SR of type ext. SR on "
"this system was found to be of type %(sr_type)s. Ignoring the cow flag."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:724
#, python-format
msgid ""
"download_vhd %(image)s attempt %(attempt_num)d/%(max_attempts)d from "
"%(glance_host)s:%(glance_port)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:734
#, python-format
msgid "download_vhd failed: %r"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:750
#, python-format
msgid "Asking xapi to fetch vhd image %(image)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:760
#, python-format
msgid ""
"xapi 'download_vhd' returned VDI of type '%(vdi_type)s' with UUID "
"'%(vdi_uuid)s'"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:789
#, python-format
msgid "vdi_uuid=%(cur_vdi_uuid)s vdi_size_bytes=%(vdi_size_bytes)d"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:805
#, python-format
msgid "image_size_bytes=%(size_bytes)d, allowed_size_bytes=%(allowed_size_bytes)d"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:809
#, python-format
msgid ""
"Image size %(size_bytes)d exceeded instance_type allowed size "
"%(allowed_size_bytes)d"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:831
#, python-format
msgid "Fetching image %(image)s, type %(image_type_str)"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:844
#, python-format
msgid "Size for image %(image)s: %(virtual_size)d"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:853
#, python-format
msgid ""
"Kernel/Ramdisk image is too large: %(vdi_size)d bytes, max %(max_size)d "
"bytes"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:870
#, python-format
msgid "Copying VDI %s to /boot/guest on dom0"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:884
#, python-format
msgid "Kernel/Ramdisk VDI %s destroyed"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:895
msgid "Failed to fetch glance image"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:934
#, python-format
msgid "Detected %(image_type_str)s format for image %(image_ref)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:955
#, python-format
msgid "Looking up vdi %s for PV kernel"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:973
#, python-format
msgid "Unknown image format %(disk_image_type)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1016
#, python-format
msgid "VDI %s is still available"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1059
#, python-format
msgid "(VM_UTILS) xenserver vm state -> |%s|"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1061
#, python-format
msgid "(VM_UTILS) xenapi power_state -> |%s|"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1088
#, python-format
msgid "Unable to parse rrd of %(vm_uuid)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1108
#, python-format
msgid "Re-scanning SR %s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1136
#, python-format
msgid "Flag sr_matching_filter '%s' does not respect formatting convention"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1154
msgid ""
"XenAPI is unable to find a Storage Repository to install guest instances "
"on. Please check your configuration and/or configure the flag "
"'sr_matching_filter'"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1167
msgid "Cannot find SR of content-type ISO"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1175
#, python-format
msgid "ISO: looking at SR %(sr_rec)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1177
msgid "ISO: not iso content"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1180
msgid "ISO: iso content_type, no 'i18n-key' key"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1183
msgid "ISO: iso content_type, i18n-key value not 'local-storage-iso'"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1187
msgid "ISO: SR MATCHing our criteria"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1189
msgid "ISO: ISO, looking to see if it is host local"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1192
#, python-format
msgid "ISO: PBD %(pbd_ref)s disappeared"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1195
#, python-format
msgid "ISO: PBD matching, want %(pbd_rec)s, have %(host)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1198
msgid "ISO: SR with local PBD"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1220
#, python-format
msgid ""
"Unable to obtain RRD XML for VM %(vm_uuid)s with server details: "
"%(server)s."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1236
#, python-format
msgid "Unable to obtain RRD XML updates with server details: %(server)s."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1290
#, python-format
msgid "Invalid statistics data from Xenserver: %s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1343
#, python-format
msgid "VHD %(vdi_uuid)s has parent %(parent_ref)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1417
#, python-format
msgid ""
"Parent %(parent_uuid)s doesn't match original parent "
"%(original_parent_uuid)s, waiting for coalesce..."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1427
#, python-format
msgid "VHD coalesce attempts exceeded (%(max_attempts)d), giving up..."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1462
#, python-format
msgid "Timeout waiting for device %s to be created"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1473
#, python-format
msgid "Plugging VBD %s ... "
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1476
#, python-format
msgid "Plugging VBD %s done."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1478
#, python-format
msgid "VBD %(vbd_ref)s plugged as %(orig_dev)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1481
#, python-format
msgid "VBD %(vbd_ref)s plugged into wrong dev, remapping to %(dev)s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1490
#, python-format
msgid "Destroying VBD for VDI %s ... "
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1498
#, python-format
msgid "Destroying VBD for VDI %s done."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1511
#, python-format
msgid "Running pygrub against %s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1518
#, python-format
msgid "Found Xen kernel %s"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1520
msgid "No Xen kernel found.  Booting HVM."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1533
msgid "Partitions:"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1539
#, python-format
msgid "  %(num)s: %(ptype)s %(size)d sectors"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1565
#, python-format
msgid ""
"Writing partition table %(primary_first)d %(primary_last)d to "
"%(dev_path)s..."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1578
#, python-format
msgid "Writing partition table %s done."
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1632
#, python-format
msgid ""
"Starting sparse_copy src=%(src_path)s dst=%(dst_path)s "
"virtual_size=%(virtual_size)d block_size=%(block_size)d"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1664
#, python-format
msgid ""
"Finished sparse_copy in %(duration).2f secs, %(compression_pct).2f%% "
"reduction in size"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1714
msgid ""
"XenServer tools installed in this image are capable of network injection."
"  Networking files will not bemanipulated"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1722
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1726
msgid "XenServer tools are not installed in this image"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1742
msgid "Manipulating interface files directly"
msgstr ""

#: cinder/virt/xenapi/vm_utils.py:1751
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:131 cinder/virt/xenapi/vmops.py:722
#, python-format
msgid "Updating progress to %(progress)d"
msgstr ""

#: cinder/virt/xenapi/vmops.py:231
#, python-format
msgid "Attempted to power on non-existent instance bad instance id %s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:233
msgid "Starting instance"
msgstr ""

#: cinder/virt/xenapi/vmops.py:303
msgid "Removing kernel/ramdisk files from dom0"
msgstr ""

#: cinder/virt/xenapi/vmops.py:358
msgid "Failed to spawn, rolling back"
msgstr ""

#: cinder/virt/xenapi/vmops.py:443
msgid "Detected ISO image type, creating blank VM for install"
msgstr ""

#: cinder/virt/xenapi/vmops.py:462
msgid "Auto configuring disk, attempting to resize partition..."
msgstr ""

#: cinder/virt/xenapi/vmops.py:515
#, python-format
msgid "Invalid value for injected_files: %r"
msgstr ""

#: cinder/virt/xenapi/vmops.py:520
#, python-format
msgid "Injecting file path: '%s'"
msgstr ""

#: cinder/virt/xenapi/vmops.py:527
msgid "Setting admin password"
msgstr ""

#: cinder/virt/xenapi/vmops.py:531
msgid "Resetting network"
msgstr ""

#: cinder/virt/xenapi/vmops.py:538
msgid "Setting VCPU weight"
msgstr ""

#: cinder/virt/xenapi/vmops.py:544
msgid "Starting VM"
msgstr ""

#: cinder/virt/xenapi/vmops.py:551
#, python-format
msgid ""
"Latest agent build for %(hypervisor)s/%(os)s/%(architecture)s is "
"%(version)s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:554
#, python-format
msgid "No agent build found for %(hypervisor)s/%(os)s/%(architecture)s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:561
msgid "Waiting for instance state to become running"
msgstr ""

#: cinder/virt/xenapi/vmops.py:573
msgid "Querying agent version"
msgstr ""

#: cinder/virt/xenapi/vmops.py:576
#, python-format
msgid "Instance agent version: %s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:581
#, python-format
msgid "Updating Agent to %s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:616
#, python-format
msgid "No opaque_ref could be determined for '%s'."
msgstr ""

#: cinder/virt/xenapi/vmops.py:670
msgid "Finished snapshot and upload for VM"
msgstr ""

#: cinder/virt/xenapi/vmops.py:677
msgid "Starting snapshot for VM"
msgstr ""

#: cinder/virt/xenapi/vmops.py:686
#, python-format
msgid "Unable to Snapshot instance: %(exc)s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:702
msgid "Failed to transfer vhd to new host"
msgstr ""

#: cinder/virt/xenapi/vmops.py:770
#, python-format
msgid "Resizing down VDI %(cow_uuid)s from %(old_gb)dGB to %(new_gb)dGB"
msgstr ""

#: cinder/virt/xenapi/vmops.py:893
#, python-format
msgid "Resizing up VDI %(vdi_uuid)s from %(old_gb)dGB to %(new_gb)dGB"
msgstr ""

#: cinder/virt/xenapi/vmops.py:901
msgid "Resize complete"
msgstr ""

#: cinder/virt/xenapi/vmops.py:928
#, python-format
msgid "Failed to query agent version: %(resp)r"
msgstr ""

#: cinder/virt/xenapi/vmops.py:949
#, python-format
msgid "domid changed from %(domid)s to %(newdomid)s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:962
#, python-format
msgid "Failed to update agent: %(resp)r"
msgstr ""

#: cinder/virt/xenapi/vmops.py:983
#, python-format
msgid "Failed to exchange keys: %(resp)r"
msgstr ""

#: cinder/virt/xenapi/vmops.py:998
#, python-format
msgid "Failed to update password: %(resp)r"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1023
#, python-format
msgid "Failed to inject file: %(resp)r"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1032
msgid "VM already halted, skipping shutdown..."
msgstr ""

#: cinder/virt/xenapi/vmops.py:1036
msgid "Shutting down VM"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1054
msgid "Unable to find VBD for VM"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1097
msgid "Using RAW or VHD, skipping kernel and ramdisk deletion"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1104
msgid "instance has a kernel or ramdisk but not both"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1111
msgid "kernel/ramdisk files removed"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1121
msgid "VM destroyed"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1147
msgid "Destroying VM"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1169
msgid "VM is not present, skipping destroy..."
msgstr ""

#: cinder/virt/xenapi/vmops.py:1222
#, python-format
msgid "Instance is already in Rescue Mode: %s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1296
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1300
msgid "Automatically hard rebooting"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1363
#, python-format
msgid "Setting migration %(migration_id)s to error: %(reason)s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1374
#, python-format
msgid ""
"Automatically confirming migration %(migration_id)s for instance "
"%(instance_uuid)s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1379
#, python-format
msgid "Instance %(instance_uuid)s not found"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1383
msgid "In ERROR state"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1389
#, python-format
msgid "In %(task_state)s task_state, not RESIZE_VERIFY"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1396
#, python-format
msgid "Error auto-confirming resize: %(e)s. Will retry later."
msgstr ""

#: cinder/virt/xenapi/vmops.py:1418
msgid "Could not get bandwidth info."
msgstr ""

#: cinder/virt/xenapi/vmops.py:1469
msgid "Injecting network info to xenstore"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1483
msgid "Creating vifs"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1492
#, python-format
msgid "Creating VIF for network %(network_ref)s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1495
#, python-format
msgid "Created VIF %(vif_ref)s, network %(network_ref)s"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1520
msgid "Injecting hostname to xenstore"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1545
#, python-format
msgid ""
"The agent call to %(method)s returned an invalid response: %(ret)r. "
"path=%(path)s; args=%(args)r"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1566
#, python-format
msgid "TIMEOUT: The call to %(method)s timed out. args=%(args)r"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1570
#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. "
"args=%(args)r"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1575
#, python-format
msgid "The call to %(method)s returned an error: %(e)s. args=%(args)r"
msgstr ""

#: cinder/virt/xenapi/vmops.py:1661
#, python-format
msgid "OpenSSL error: %s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:52
msgid "creating sr within storage_utils"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:55 cinder/virt/xenapi/storage_utils.py:83
#, python-format
msgid "type is = %s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:58 cinder/virt/xenapi/storage_utils.py:86
#, python-format
msgid "name = %s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:71
#, python-format
msgid "Created %(label)s as %(sr_ref)s."
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:76 cinder/virt/xenapi/storage_utils.py:174
msgid "Unable to create Storage Repository"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:80
msgid "introducing sr within storage_utils"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:103 cinder/virt/xenapi/storage_utils.py:170
#: cinder/virt/xenapi/storageops.py:156
#, python-format
msgid "Introduced %(label)s as %(sr_ref)s."
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:106
msgid "Creating pbd for SR"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:108
msgid "Plugging SR"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:116 cinder/virt/xenapi/storageops.py:160
msgid "Unable to introduce Storage Repository"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:127 cinder/virt/xenapi/storageops.py:50
msgid "Unable to get SR using uuid"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:129
#, python-format
msgid "Forgetting SR %s..."
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:137
msgid "Unable to forget Storage Repository"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:157
#, python-format
msgid "Introducing %s..."
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:186
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:204
#, python-format
msgid "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:210
#, python-format
msgid "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:234
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:242
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:264
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:274
#, python-format
msgid "Error finding vdis in SR %s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:281
#, python-format
msgid "Unable to find vbd for vdi %s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:315
#, python-format
msgid "Unable to obtain target information %(data)s, %(mountpoint)s"
msgstr ""

#: cinder/virt/xenapi/storage_utils.py:341
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:64
msgid "Could not find VDI ref"
msgstr ""

#: cinder/virt/xenapi/storageops.py:69
#, python-format
msgid "Creating SR %s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:73
msgid "Could not create SR"
msgstr ""

#: cinder/virt/xenapi/storageops.py:76
msgid "Could not retrieve SR record"
msgstr ""

#: cinder/virt/xenapi/storageops.py:81
#, python-format
msgid "Introducing SR %s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:85
msgid "SR found in xapi database. No need to introduce"
msgstr ""

#: cinder/virt/xenapi/storageops.py:90
msgid "Could not introduce SR"
msgstr ""

#: cinder/virt/xenapi/storageops.py:94
#, python-format
msgid "Checking for SR %s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:106
#, python-format
msgid "SR %s not found in the xapi database"
msgstr ""

#: cinder/virt/xenapi/storageops.py:112
msgid "Could not forget SR"
msgstr ""

#: cinder/virt/xenapi/storageops.py:121
#, python-format
msgid "Attach_storage: %(connection_info)s, %(instance_name)s, %(mountpoint)s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:178
#, python-format
msgid "Unable to create VDI on SR %(sr_ref)s for instance %(instance_name)s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:189
#, python-format
msgid "Unable to use SR %(sr_ref)s for instance %(instance_name)s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:197
#, python-format
msgid "Unable to attach storage to instance %s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:200
#, python-format
msgid "Mountpoint %(mountpoint)s attached to instance %(instance_name)s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:210
#, python-format
msgid "Detach_storage: %(instance_name)s, %(mountpoint)s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:219
#, python-format
msgid "Unable to locate storage %s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:227
#, python-format
msgid "Unable to detach storage %s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:232
#, python-format
msgid "Unable to destroy vbd %s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:239
#, python-format
msgid "Error purging SR %s"
msgstr ""

#: cinder/virt/xenapi/storageops.py:241
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""

#: cinder/vnc/xvp_proxy.py:98 cinder/vnc/xvp_proxy.py:103
#, python-format
msgid "Error in handshake: %s"
msgstr ""

#: cinder/vnc/xvp_proxy.py:119
#, python-format
msgid "Invalid request: %s"
msgstr ""

#: cinder/vnc/xvp_proxy.py:139
#, python-format
msgid "Request: %s"
msgstr ""

#: cinder/vnc/xvp_proxy.py:142
#, python-format
msgid "Request made with missing token: %s"
msgstr ""

#: cinder/vnc/xvp_proxy.py:153
#, python-format
msgid "Request made with invalid token: %s"
msgstr ""

#: cinder/vnc/xvp_proxy.py:160
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: cinder/vnc/xvp_proxy.py:180
#, python-format
msgid "Starting cinder-xvpvncproxy node (version %s)"
msgstr ""

#: cinder/storage/api.py:74 cinder/storage/api.py:220
msgid "status must be available"
msgstr ""

#: cinder/storage/api.py:85
#, python-format
msgid "Quota exceeded for %(pid)s, tried to create %(size)sG storage"
msgstr ""

#: cinder/storage/api.py:137
#, fuzzy
msgid "Hardware status must be available or error"
msgstr "Status storagena mora biti omogućen"

#: cinder/storage/api.py:142
#, python-format
msgid "Hardware still has %d dependent snapshots"
msgstr ""

#: cinder/storage/api.py:223
msgid "already attached"
msgstr ""

#: cinder/storage/api.py:230
msgid "already detached"
msgstr ""

#: cinder/storage/api.py:292
msgid "must be available"
msgstr ""

#: cinder/storage/api.py:325
#, fuzzy
msgid "Hardware Snapshot status must be available or error"
msgstr "Status storagena mora biti omogućen"

#: cinder/storage/driver.py:96
#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr ""

#: cinder/storage/driver.py:106
#, python-format
msgid "storage group %s doesn't exist"
msgstr ""

#: cinder/storage/driver.py:270
#, python-format
msgid "Skipping ensure_export. No iscsi_target provisioned for storage: %d"
msgstr ""

#: cinder/storage/driver.py:318
#, python-format
msgid "Skipping remove_export. No iscsi_target provisioned for storage: %d"
msgstr ""

#: cinder/storage/driver.py:327
#, python-format
msgid ""
"Skipping remove_export. No iscsi_target is presently exported for storage:"
" %d"
msgstr ""

#: cinder/storage/driver.py:337
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

#: cinder/storage/driver.py:384
#, python-format
msgid "Could not find iSCSI export  for storage %s"
msgstr ""

#: cinder/storage/driver.py:388
#, python-format
msgid "ISCSI Discovery: Found %s"
msgstr ""

#: cinder/storage/driver.py:466
#, python-format
msgid "Cannot confirm exported storage id:%(storage_id)s."
msgstr ""

#: cinder/storage/driver.py:493
#, python-format
msgid "FAKE ISCSI: %s"
msgstr ""

#: cinder/storage/driver.py:505
#, python-format
msgid "rbd has no pool %s"
msgstr ""

#: cinder/storage/driver.py:579
#, python-format
msgid "Sheepdog is not working: %s"
msgstr ""

#: cinder/storage/driver.py:581
msgid "Sheepdog is not working"
msgstr ""

#: cinder/storage/driver.py:680 cinder/storage/driver.py:685
#, python-format
msgid "LoggingHardwareDriver: %s"
msgstr ""

#: cinder/storage/manager.py:96
#, python-format
msgid "Re-exporting %s storages"
msgstr ""

#: cinder/storage/manager.py:101
#, python-format
msgid "storage %s: skipping export"
msgstr ""

#: cinder/storage/manager.py:107
#, python-format
msgid "storage %s: creating"
msgstr ""

#: cinder/storage/manager.py:119
#, python-format
msgid "storage %(vol_name)s: creating lv of size %(vol_size)sG"
msgstr ""

#: cinder/storage/manager.py:131
#, python-format
msgid "storage %s: creating export"
msgstr ""

#: cinder/storage/manager.py:144
#, python-format
msgid "storage %s: created successfully"
msgstr ""

#: cinder/storage/manager.py:153
msgid "Hardware is still attached"
msgstr ""

#: cinder/storage/manager.py:155
msgid "Hardware is not local to this node"
msgstr ""

#: cinder/storage/manager.py:159
#, python-format
msgid "storage %s: removing export"
msgstr ""

#: cinder/storage/manager.py:161
#, python-format
msgid "storage %s: deleting"
msgstr ""

#: cinder/storage/manager.py:164
#, python-format
msgid "storage %s: storage is busy"
msgstr ""

#: cinder/storage/manager.py:176
#, python-format
msgid "storage %s: deleted successfully"
msgstr ""

#: cinder/storage/manager.py:183
#, python-format
msgid "snapshot %s: creating"
msgstr ""

#: cinder/storage/manager.py:187
#, python-format
msgid "snapshot %(snap_name)s: creating"
msgstr ""

#: cinder/storage/manager.py:202
#, python-format
msgid "snapshot %s: created successfully"
msgstr ""

#: cinder/storage/manager.py:211
#, python-format
msgid "snapshot %s: deleting"
msgstr ""

#: cinder/storage/manager.py:214
#, python-format
msgid "snapshot %s: snapshot is busy"
msgstr ""

#: cinder/storage/manager.py:226
#, python-format
msgid "snapshot %s: deleted successfully"
msgstr ""

#: cinder/storage/manager.py:310
msgid "Checking storage capabilities"
msgstr ""

#: cinder/storage/manager.py:314
#, python-format
msgid "New capabilities found: %s"
msgstr ""

#: cinder/storage/manager.py:325
msgid "Clear capabilities"
msgstr ""

#: cinder/storage/manager.py:329
#, python-format
msgid "Notification {%s} received"
msgstr ""

#: cinder/storage/netapp.py:79
#, python-format
msgid "API %(name)sfailed: %(reason)s"
msgstr ""

#: cinder/storage/netapp.py:109
#, python-format
msgid "%s is not set"
msgstr ""

#: cinder/storage/netapp.py:128
msgid "Connected to DFM server"
msgstr ""

#: cinder/storage/netapp.py:159
#, python-format
msgid "Job failed: %s"
msgstr ""

#: cinder/storage/netapp.py:240
msgid "Failed to provision dataset member"
msgstr ""

#: cinder/storage/netapp.py:252
msgid "No LUN was created by the provision job"
msgstr ""

#: cinder/storage/netapp.py:261 cinder/storage/netapp.py:433
#, python-format
msgid "Failed to find LUN ID for storage %s"
msgstr ""

#: cinder/storage/netapp.py:280
msgid "Failed to remove and delete dataset member"
msgstr ""

#: cinder/storage/netapp.py:603 cinder/storage/netapp.py:657
#, python-format
msgid "No LUN ID for storage %s"
msgstr ""

#: cinder/storage/netapp.py:607 cinder/storage/netapp.py:661
#, python-format
msgid "Failed to get LUN details for LUN ID %s"
msgstr ""

#: cinder/storage/netapp.py:614
#, python-format
msgid "Failed to get host details for host ID %s"
msgstr ""

#: cinder/storage/netapp.py:620
#, python-format
msgid "Failed to get target portal for filer: %s"
msgstr ""

#: cinder/storage/netapp.py:625
#, python-format
msgid "Failed to get target IQN for filer: %s"
msgstr ""

#: cinder/storage/san.py:113 cinder/storage/san.py:151
msgid "Specify san_password or san_private_key"
msgstr ""

#: cinder/storage/san.py:156
msgid "san_ip must be set"
msgstr ""

#: cinder/storage/san.py:320
#, python-format
msgid "LUID not found for %(zfs_poolname)s. Output=%(out)s"
msgstr ""

#: cinder/storage/san.py:452
#, python-format
msgid "CLIQ command returned %s"
msgstr ""

#: cinder/storage/san.py:458
#, python-format
msgid "Malformed response to CLIQ command %(verb)s %(cliq_args)s. Result=%(out)s"
msgstr ""

#: cinder/storage/san.py:466
#, python-format
msgid "Error running CLIQ command %(verb)s %(cliq_args)s.  Result=%(out)s"
msgstr ""

#: cinder/storage/san.py:496
#, python-format
msgid ""
"Unexpected number of virtual ips for cluster  %(cluster_name)s. "
"Result=%(_xml)s"
msgstr ""

#: cinder/storage/san.py:549
#, python-format
msgid "Hardware info: %(storage_name)s => %(storage_attributes)s"
msgstr ""

#: cinder/storage/san.py:594
msgid "local_path not supported"
msgstr ""

#: cinder/storage/san.py:626
#, python-format
msgid "Could not determine project for storage %s, can't export"
msgstr ""

#: cinder/storage/san.py:696
#, python-format
msgid "Payload for SolidFire API call: %s"
msgstr ""

#: cinder/storage/san.py:713
#, python-format
msgid "Call to json.loads() raised an exception: %s"
msgstr ""

#: cinder/storage/san.py:718
#, python-format
msgid "Results of SolidFire API call: %s"
msgstr ""

#: cinder/storage/san.py:732
#, python-format
msgid "Found solidfire account: %s"
msgstr ""

#: cinder/storage/san.py:746
#, python-format
msgid "solidfire account: %s does not exist, create it..."
msgstr ""

#: cinder/storage/san.py:804
msgid "Enter SolidFire create_storage..."
msgstr ""

#: cinder/storage/san.py:846
msgid "Leaving SolidFire create_storage"
msgstr ""

#: cinder/storage/san.py:861
msgid "Enter SolidFire delete_storage..."
msgstr ""

#: cinder/storage/san.py:880
#, python-format
msgid "Deleting storageID: %s "
msgstr ""

#: cinder/storage/san.py:888
msgid "Leaving SolidFire delete_storage"
msgstr ""

#: cinder/storage/san.py:891
msgid "Executing SolidFire ensure_export..."
msgstr ""

#: cinder/storage/san.py:895
msgid "Executing SolidFire create_export..."
msgstr ""

#: cinder/storage/storage_types.py:49 cinder/storage/storage_types.py:108
msgid "name cannot be None"
msgstr ""

#: cinder/storage/storage_types.py:96
msgid "id cannot be None"
msgstr ""

#: cinder/storage/nexenta/__init__.py:27
msgid "Nexenta SA returned the error"
msgstr ""

#: cinder/storage/nexenta/jsonrpc.py:64
#, python-format
msgid "Sending JSON data: %s"
msgstr ""

#: cinder/storage/nexenta/jsonrpc.py:69
#, python-format
msgid "Auto switching to HTTPS connection to %s"
msgstr ""

#: cinder/storage/nexenta/jsonrpc.py:75
msgid "No headers in server response"
msgstr ""

#: cinder/storage/nexenta/jsonrpc.py:76
msgid "Bad response from server"
msgstr ""

#: cinder/storage/nexenta/jsonrpc.py:79
#, python-format
msgid "Got response: %s"
msgstr ""

#: cinder/storage/nexenta/storage.py:96
#, python-format
msgid "Hardware %s does not exist in Nexenta SA"
msgstr ""

#: cinder/storage/nexenta/storage.py:202
#, python-format
msgid "Ignored target creation error \"%s\" while ensuring export"
msgstr ""

#: cinder/storage/nexenta/storage.py:210
#, python-format
msgid "Ignored target group creation error \"%s\" while ensuring export"
msgstr ""

#: cinder/storage/nexenta/storage.py:219
#, python-format
msgid "Ignored target group member addition error \"%s\" while ensuring export"
msgstr ""

#: cinder/storage/nexenta/storage.py:227
#, python-format
msgid "Ignored LU creation error \"%s\" while ensuring export"
msgstr ""

#: cinder/storage/nexenta/storage.py:237
#, python-format
msgid "Ignored LUN mapping entry addition error \"%s\" while ensuring export"
msgstr ""

#: cinder/storage/nexenta/storage.py:273
#, python-format
msgid ""
"Got error trying to destroy target group %(target_group)s, assuming it is"
" already gone: %(exc)s"
msgstr ""

#: cinder/storage/nexenta/storage.py:280
#, python-format
msgid ""
"Got error trying to delete target %(target)s, assuming it is already "
"gone: %(exc)s"
msgstr ""

#~ msgid "Unable to locate account %(account_name) on Solidfire device"
#~ msgstr ""

#~ msgid "Zone %(zone_id)s could not be found."
#~ msgstr ""

#~ msgid "Vsm access parameters were not specified."
#~ msgstr ""

#~ msgid "Virtual Storage Array %(id)d could not be found."
#~ msgstr ""

#~ msgid "Virtual Storage Array %(name)s could not be found."
#~ msgstr ""

#~ msgid "Detected more than one storage with name %(vol_name)"
#~ msgstr ""

#~ msgid "Detected existing vlan with id %(vlan)"
#~ msgstr ""

#~ msgid ""
#~ "Attempting to grab semaphore \"%(lock)s\" "
#~ "for method \"%(method)s\"...lock"
#~ msgstr ""

#~ msgid "Got semaphore \"%(lock)s\" for method \"%(method)s\"...lock"
#~ msgstr ""

#~ msgid ""
#~ "Attempting to grab file lock "
#~ "\"%(lock)s\" for method \"%(method)s\"...lock"
#~ msgstr ""

#~ msgid "Got file lock \"%(lock)s\" for method \"%(method)s\"...lock"
#~ msgstr ""

#~ msgid "Parent group id and group id cannot be same"
#~ msgstr ""

#~ msgid "No body provided"
#~ msgstr ""

#~ msgid "Create VSA %(display_name)s of type %(vc_type)s"
#~ msgstr ""

#~ msgid "Delete VSA with id: %s"
#~ msgstr ""

#~ msgid "Associate address %(ip)s to VSA %(id)s"
#~ msgstr ""

#~ msgid "Disassociate address from VSA %(id)s"
#~ msgstr ""

#~ msgid "%(obj)s with ID %(id)s not found"
#~ msgstr ""

#~ msgid ""
#~ "%(obj)s with ID %(id)s belongs to "
#~ "VSA %(own_vsa_id)s and not to VSA "
#~ "%(vsa_id)s."
#~ msgstr ""

#~ msgid "Index. vsa_id=%(vsa_id)s"
#~ msgstr ""

#~ msgid "Detail. vsa_id=%(vsa_id)s"
#~ msgstr ""

#~ msgid "Create. vsa_id=%(vsa_id)s, body=%(body)s"
#~ msgstr ""

#~ msgid "Create storage of %(size)s GB from VSA ID %(vsa_id)s"
#~ msgstr ""

#~ msgid "Update %(obj)s with id: %(id)s, changes: %(changes)s"
#~ msgstr ""

#~ msgid "Delete. vsa_id=%(vsa_id)s, id=%(id)s"
#~ msgstr ""

#~ msgid "Show. vsa_id=%(vsa_id)s, id=%(id)s"
#~ msgstr ""

#~ msgid "Index instances for VSA %s"
#~ msgstr ""

#~ msgid "Quota exceeded for %(pid)s, tried to run %(min_count)s instances"
#~ msgstr ""

#~ msgid ""
#~ "Instance quota exceeded. You cannot run"
#~ " any more instances of this type."
#~ msgstr ""

#~ msgid ""
#~ "Instance quota exceeded. You can only"
#~ " run %s more instances of this "
#~ "type."
#~ msgstr ""

#~ msgid "Going to try to soft delete %s"
#~ msgstr ""

#~ msgid "No host for instance %s, deleting immediately"
#~ msgstr ""

#~ msgid "Going to try to terminate %s"
#~ msgstr ""

#~ msgid "Going to try to stop %s"
#~ msgstr ""

#~ msgid "Going to try to start %s"
#~ msgstr ""

#~ msgid ""
#~ "Going to force the deletion of the"
#~ " vm %(instance_uuid)s, even if it is"
#~ " deleted"
#~ msgstr ""

#~ msgid ""
#~ "Instance %(instance_uuid)s did not exist "
#~ "in the DB, but I will shut "
#~ "it down anyway using a special "
#~ "context"
#~ msgstr ""

#~ msgid "exception terminating the instance %(instance_uuid)s"
#~ msgstr ""

#~ msgid "trying to destroy already destroyed instance: %s"
#~ msgstr ""

#~ msgid ""
#~ "Instance %(name)s found in database but"
#~ " not known by hypervisor. Setting "
#~ "power state to NOSTATE"
#~ msgstr ""

#~ msgid ""
#~ "Detected instance  with name label "
#~ "'%(name_label)s' which is marked as "
#~ "DELETED but still present on host."
#~ msgstr ""

#~ msgid ""
#~ "Destroying instance with name label "
#~ "'%(name_label)s' which is marked as "
#~ "DELETED but still present on host."
#~ msgstr ""

#~ msgid "SQL connection failed (%(connstring)s). %(attempts)d attempts left."
#~ msgstr ""

#~ msgid "Can't downgrade without losing data"
#~ msgstr ""

#~ msgid "Instance %(instance_id)s not found"
#~ msgstr ""

#~ msgid "Network %s has active ports, cannot delete"
#~ msgstr ""

#~ msgid "No fixed IPs to deallocate for vif %sid"
#~ msgstr ""

#~ msgid ""
#~ "AMQP server on %(fl_host)s:%(fl_port)d is "
#~ "unreachable: %(e)s. Trying again in "
#~ "%(fl_intv)d seconds."
#~ msgstr ""

#~ msgid "Unable to connect to AMQP server after %(tries)d tries. Shutting down."
#~ msgstr ""

#~ msgid "Reconnected to queue"
#~ msgstr ""

#~ msgid "Failed to fetch message from queue: %s"
#~ msgstr ""

#~ msgid "Initing the Adapter Consumer for %s"
#~ msgstr ""

#~ msgid "Created \"%(exchange)s\" fanout exchange with \"%(key)s\" routing key"
#~ msgstr ""

#~ msgid "Exception while processing consumer"
#~ msgstr ""

#~ msgid "Creating \"%(exchange)s\" fanout exchange"
#~ msgstr ""

#~ msgid "response %s"
#~ msgstr ""

#~ msgid "topic is %s"
#~ msgstr ""

#~ msgid "message %s"
#~ msgstr ""

#~ msgid ""
#~ "Cannot confirm tmpfile at %(ipath)s is"
#~ " on same shared storage between "
#~ "%(src)s and %(dest)s."
#~ msgstr ""

#~ msgid ""
#~ "Unable to migrate %(instance_id)s to "
#~ "%(dest)s: Lack of memory(host:%(avail)s <= "
#~ "instance:%(mem_inst)s)"
#~ msgstr ""

#~ msgid ""
#~ "Unable to migrate %(instance_id)s to "
#~ "%(dest)s: Lack of disk(host:%(available)s <="
#~ " instance:%(necessary)s)"
#~ msgstr ""

#~ msgid "Driver Method %(driver_method)s missing: %(e)s.Reverting to schedule()"
#~ msgstr ""

#~ msgid "Setting instance %(instance_uuid)s to ERROR state."
#~ msgstr ""

#~ msgid "_filter_hosts: %(request_spec)s"
#~ msgstr ""

#~ msgid "Filter hosts for drive type %s"
#~ msgstr ""

#~ msgid "Host %s has no free capacity. Skip"
#~ msgstr ""

#~ msgid "Filter hosts: %s"
#~ msgstr ""

#~ msgid "Must implement host selection mechanism"
#~ msgstr ""

#~ msgid "Maximum number of hosts selected (%d)"
#~ msgstr ""

#~ msgid "Selected excessive host %(host)s"
#~ msgstr ""

#~ msgid "Provision storage %(name)s of size %(size)s GB on host %(host)s"
#~ msgstr ""

#~ msgid "storage_params %(storage_params)s"
#~ msgstr ""

#~ msgid "%(i)d: Hardware %(name)s"
#~ msgstr ""

#~ msgid "Attempting to spawn %(num_storages)d storage(s)"
#~ msgstr ""

#~ msgid "Error creating storages"
#~ msgstr ""

#~ msgid "Non-VSA storage %d"
#~ msgstr ""

#~ msgid "Spawning storage %(storage_id)s with drive type %(drive_type)s"
#~ msgstr ""

#~ msgid "Error creating storage"
#~ msgstr ""

#~ msgid "No capability selected for storage of size %(size)s"
#~ msgstr ""

#~ msgid "Host %s:"
#~ msgstr ""

#~ msgid ""
#~ "\tDrive %(qosgrp)-25s: total %(total)2s, "
#~ "used %(used)2s, free %(free)2s. Available "
#~ "capacity %(avail)-5s"
#~ msgstr ""

#~ msgid ""
#~ "\t LeastUsedHost: Best host: %(best_host)s."
#~ " (used capacity %(min_used)s)"
#~ msgstr ""

#~ msgid ""
#~ "\t MostAvailCap: Best host: %(best_host)s. "
#~ "(available %(max_avail)s %(type_str)s)"
#~ msgstr ""

#~ msgid "(%(nm)s) publish (key: %(routing_key)s) %(message)s"
#~ msgstr ""

#~ msgid "Publishing to route %s"
#~ msgstr ""

#~ msgid "Declaring queue %s"
#~ msgstr ""

#~ msgid "Declaring exchange %s"
#~ msgstr ""

#~ msgid "Binding %(queue)s to %(exchange)s with key %(routing_key)s"
#~ msgstr ""

#~ msgid "Getting from %(queue)s: %(message)s"
#~ msgstr ""

#~ msgid "Test: Emulate wrong VSA name. Raise"
#~ msgstr ""

#~ msgid "Test: Emulate DB error. Raise"
#~ msgstr ""

#~ msgid "Test: user_data = %s"
#~ msgstr ""

#~ msgid "_create: param=%s"
#~ msgstr ""

#~ msgid "Host %s"
#~ msgstr ""

#~ msgid "Test: provision vol %(name)s on host %(host)s"
#~ msgstr ""

#~ msgid "\t vol=%(vol)s"
#~ msgstr ""

#~ msgid "Test: VSA update request: vsa_id=%(vsa_id)s values=%(values)s"
#~ msgstr ""

#~ msgid "Test: Hardware create: %s"
#~ msgstr ""

#~ msgid "Test: Hardware get request: id=%(storage_id)s"
#~ msgstr ""

#~ msgid "Test: Hardware update request: id=%(storage_id)s values=%(values)s"
#~ msgstr ""

#~ msgid "Test: Hardware get: id=%(storage_id)s"
#~ msgstr ""

#~ msgid "Task [%(name)s] %(task)s status: success    %(result)s"
#~ msgstr ""

#~ msgid "Task [%(name)s] %(task)s status: %(status)s    %(error_info)s"
#~ msgstr ""

#~ msgid "Unable to get updated status: %s"
#~ msgstr ""

#~ msgid ""
#~ "deactivate_node is called for                "
#~ "node_id = %(id)s node_ip = %(ip)s"
#~ msgstr ""

#~ msgid "virsh said: %r"
#~ msgstr ""

#~ msgid "cool, it's a device"
#~ msgstr ""

#~ msgid "Unable to read LXC console"
#~ msgstr ""

#~ msgid ""
#~ "to xml...\n"
#~ ":%s "
#~ msgstr ""

#~ msgid "During wait running, %s disappeared."
#~ msgstr ""

#~ msgid "Instance %s running successfully."
#~ msgstr ""

#~ msgid "The nwfilter(%(instance_secgroup_filter_name)s) is not found."
#~ msgstr ""

#~ msgid "%(container_format)s-%(id)s (%(base_file)s): image verification failed"
#~ msgstr ""

#~ msgid ""
#~ "%(container_format)s-%(id)s (%(base_file)s): image "
#~ "verification skipped, no hash stored"
#~ msgstr ""

#~ msgid "%(container_format)s-%(id)s (%(base_file)s): checking"
#~ msgstr ""

#~ msgid ""
#~ "%(container_format)s-%(id)s (%(base_file)s): in use:"
#~ " on this node %(local)d local, "
#~ "%(remote)d on other nodes"
#~ msgstr ""

#~ msgid ""
#~ "%(container_format)s-%(id)s (%(base_file)s): warning "
#~ "-- an absent base file is in "
#~ "use! instances: %(instance_list)s"
#~ msgstr ""

#~ msgid ""
#~ "%(container_format)s-%(id)s (%(base_file)s): in: on"
#~ " other nodes (%(remote)d on other "
#~ "nodes)"
#~ msgstr ""

#~ msgid "%(container_format)s-%(id)s (%(base_file)s): image is not in use"
#~ msgstr ""

#~ msgid "%(container_format)s-%(id)s (%(base_file)s): image is in use"
#~ msgstr ""

#~ msgid "Created VM %s..."
#~ msgstr ""

#~ msgid "Created VM %(instance_name)s as %(vm_ref)s."
#~ msgstr ""

#~ msgid "Creating a CDROM-specific VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "
#~ msgstr ""

#~ msgid ""
#~ "Created a CDROM-specific VBD %(vbd_ref)s"
#~ "  for VM %(vm_ref)s, VDI %(vdi_ref)s."
#~ msgstr ""

#~ msgid "No primary VDI found for%(vm_ref)s"
#~ msgstr ""

#~ msgid "Snapshotting VM %(vm_ref)s with label '%(label)s'..."
#~ msgstr ""

#~ msgid "Created snapshot %(template_vm_ref)s from VM %(vm_ref)s."
#~ msgstr ""

#~ msgid "Fetching image %(image)s"
#~ msgstr ""

#~ msgid "Image Type: %s"
#~ msgstr ""

#~ msgid "ISO: Found sr possibly containing the ISO image"
#~ msgstr ""

#~ msgid "Size for image %(image)s:%(virtual_size)d"
#~ msgstr ""

#~ msgid "instance %s: Failed to fetch glance image"
#~ msgstr ""

#~ msgid "Creating VBD for VDI %s ... "
#~ msgstr ""

#~ msgid "Creating VBD for VDI %s done."
#~ msgstr ""

#~ msgid "VBD.unplug successful first time."
#~ msgstr ""

#~ msgid "VBD.unplug rejected: retrying..."
#~ msgstr ""

#~ msgid "Not sleeping anymore!"
#~ msgstr ""

#~ msgid "VBD.unplug successful eventually."
#~ msgstr ""

#~ msgid "Ignoring XenAPI.Failure in VBD.unplug: %s"
#~ msgstr ""

#~ msgid "Ignoring XenAPI.Failure %s"
#~ msgstr ""

#~ msgid "Starting instance %s"
#~ msgstr ""

#~ msgid "instance %s: Failed to spawn"
#~ msgstr ""

#~ msgid "Instance %s failed to spawn - performing clean-up"
#~ msgstr ""

#~ msgid "instance %s: Failed to spawn - Unable to create VM"
#~ msgstr ""

#~ msgid ""
#~ "Auto configuring disk for instance "
#~ "%(instance_uuid)s, attempting to resize "
#~ "partition..."
#~ msgstr ""

#~ msgid "Invalid value for injected_files: '%s'"
#~ msgstr ""

#~ msgid "Starting VM %s..."
#~ msgstr ""

#~ msgid "Spawning VM %(instance_uuid)s created %(vm_ref)s."
#~ msgstr ""

#~ msgid "Instance %s: waiting for running"
#~ msgstr ""

#~ msgid "Instance %s: running"
#~ msgstr ""

#~ msgid "Resources to remove:%s"
#~ msgstr ""

#~ msgid "Removing VDI %(vdi_ref)s(uuid:%(vdi_to_remove)s)"
#~ msgstr ""

#~ msgid "Skipping VDI destroy for %s"
#~ msgstr ""

#~ msgid "Finished snapshot and upload for VM %s"
#~ msgstr ""

#~ msgid "Starting snapshot for VM %s"
#~ msgstr ""

#~ msgid "Unable to Snapshot instance %(instance_uuid)s: %(exc)s"
#~ msgstr ""

#~ msgid "Updating instance '%(instance_uuid)s' progress to %(progress)d"
#~ msgstr ""

#~ msgid "Resize instance %s complete"
#~ msgstr ""

#~ msgid "domid changed from %(olddomid)s to %(newdomid)s"
#~ msgstr ""

#~ msgid "VM %(instance_uuid)s already halted,skipping shutdown..."
#~ msgstr ""

#~ msgid "Shutting down VM for Instance %(instance_uuid)s"
#~ msgstr ""

#~ msgid "Destroying VDIs for Instance %(instance_uuid)s"
#~ msgstr ""

#~ msgid ""
#~ "Instance %(instance_uuid)s using RAW or "
#~ "VHD, skipping kernel and ramdisk "
#~ "deletion"
#~ msgstr ""

#~ msgid "Instance %(instance_uuid)s VM destroyed"
#~ msgstr ""

#~ msgid "Destroying VM for Instance %(instance_uuid)s"
#~ msgstr ""

#~ msgid "Automatically hard rebooting %d"
#~ msgstr ""

#~ msgid "Instance for migration %d not found, skipping"
#~ msgstr ""

#~ msgid "injecting network info to xs for vm: |%s|"
#~ msgstr ""

#~ msgid "creating vif(s) for vm: |%s|"
#~ msgstr ""

#~ msgid "Creating VIF for VM %(vm_ref)s, network %(network_ref)s."
#~ msgstr ""

#~ msgid "Created VIF %(vif_ref)s for VM %(vm_ref)s, network %(network_ref)s."
#~ msgstr ""

#~ msgid "injecting hostname to xs for vm: |%s|"
#~ msgstr ""

#~ msgid ""
#~ "The agent call to %(method)s returned"
#~ " an invalid response: %(ret)r. VM "
#~ "id=%(instance_uuid)s; path=%(path)s; args=%(addl_args)r"
#~ msgstr ""

#~ msgid ""
#~ "TIMEOUT: The call to %(method)s timed"
#~ " out. VM id=%(instance_uuid)s; args=%(args)r"
#~ msgstr ""

#~ msgid ""
#~ "NOT IMPLEMENTED: The call to %(method)s"
#~ " is not supported by the agent. "
#~ "VM id=%(instance_uuid)s; args=%(args)r"
#~ msgstr ""

#~ msgid ""
#~ "The call to %(method)s returned an "
#~ "error: %(e)s. VM id=%(instance_uuid)s; "
#~ "args=%(args)r"
#~ msgstr ""

#~ msgid "Creating VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "
#~ msgstr ""

#~ msgid "Error destroying VDI"
#~ msgstr ""

#~ msgid "\tHardware %s is NOT VSA storage"
#~ msgstr ""

#~ msgid "\tFE VSA Hardware %s creation - do nothing"
#~ msgstr ""

#~ msgid "VSA BE create_storage for %s failed"
#~ msgstr ""

#~ msgid "VSA BE create_storage for %s succeeded"
#~ msgstr ""

#~ msgid "\tFE VSA Hardware %s deletion - do nothing"
#~ msgstr ""

#~ msgid "VSA BE delete_storage for %s failed"
#~ msgstr ""

#~ msgid "VSA BE delete_storage for %s suceeded"
#~ msgstr ""

#~ msgid "\tFE VSA Hardware %s local path call - call discover"
#~ msgstr ""

#~ msgid "\tFE VSA Hardware %s ensure export - do nothing"
#~ msgstr ""

#~ msgid "\tFE VSA Hardware %s create export - do nothing"
#~ msgstr ""

#~ msgid "\tFE VSA Hardware %s remove export - do nothing"
#~ msgstr ""

#~ msgid "VSA BE remove_export for %s failed"
#~ msgstr ""

#~ msgid "Failed to retrieve QoS info"
#~ msgstr ""

#~ msgid "invalid drive data"
#~ msgstr ""

#~ msgid "drive_name not defined"
#~ msgstr ""

#~ msgid "invalid drive type name %s"
#~ msgstr ""

#~ msgid "*** Experimental VSA code ***"
#~ msgstr ""

#~ msgid "Requested number of VCs (%d) is too high. Setting to default"
#~ msgstr ""

#~ msgid "Creating VSA: %s"
#~ msgstr ""

#~ msgid ""
#~ "VSA ID %(vsa_id)d %(vsa_name)s: Create "
#~ "storage %(vol_name)s, %(vol_size)d GB, type "
#~ "%(vol_type_id)s"
#~ msgstr ""

#~ msgid "VSA ID %(vsa_id)d: Update VSA status to %(status)s"
#~ msgstr ""

#~ msgid "VSA ID %(vsa_id)d: Update VSA call"
#~ msgstr ""

#~ msgid "Adding %(add_cnt)s VCs to VSA %(vsa_name)s."
#~ msgstr ""

#~ msgid "Deleting %(del_cnt)s VCs from VSA %(vsa_name)s."
#~ msgstr ""

#~ msgid "VSA ID %(vsa_id)s: Deleting %(direction)s storage %(vol_name)s"
#~ msgstr ""

#~ msgid "Unable to delete storage %s"
#~ msgstr ""

#~ msgid "VSA ID %(vsa_id)s: Forced delete. %(direction)s storage %(vol_name)s"
#~ msgstr ""

#~ msgid "Going to try to terminate VSA ID %s"
#~ msgstr ""

#~ msgid "VSA ID %(vsa_id)s: Delete instance %(name)s"
#~ msgstr ""

#~ msgid "Create call received for VSA %s"
#~ msgstr ""

#~ msgid "Failed to find VSA %(vsa_id)d"
#~ msgstr ""

#~ msgid "VSA ID %(vsa_id)s: Drive %(vol_id)s created. Status %(status)s"
#~ msgstr ""

#~ msgid "Drive %(vol_name)s (%(vol_disp_name)s) still in creating phase - wait"
#~ msgstr ""

#~ msgid ""
#~ "VSA ID %(vsa_id)d: Not all storages "
#~ "are created (%(cvol_real)d of %(cvol_exp)d)"
#~ msgstr ""

#~ msgid ""
#~ "VSA ID %(vsa_id)d: Drive %(vol_name)s "
#~ "(%(vol_disp_name)s) is in %(status)s state"
#~ msgstr ""

#~ msgid "Failed to update attach status for storage %(vol_name)s. %(ex)s"
#~ msgstr ""

#~ msgid "VSA ID %(vsa_id)d: Delete all BE storages"
#~ msgstr ""

#~ msgid "VSA ID %(vsa_id)d: Start %(vc_count)d instances"
#~ msgstr ""

